// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/payment-methods": {
            "get": {
                "description": "Mendapatkan daftar semua metode pembayaran yang tersedia",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Methods"
                ],
                "summary": "Lihat Semua Metode Pembayaran",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/github_com_ybb-platform_payment-service_internal_domain_entities.PaymentMethodEntity"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Menambahkan bank atau metode pembayaran baru ke database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Methods"
                ],
                "summary": "Tambah Metode Pembayaran Baru",
                "parameters": [
                    {
                        "description": "Data Payment Method",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ybb-platform_payment-service_internal_domain_entities.PaymentMethodEntity"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/github_com_ybb-platform_payment-service_internal_domain_entities.PaymentMethodEntity"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payment-methods/{id}": {
            "put": {
                "description": "Mengubah data bank atau metode pembayaran berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Methods"
                ],
                "summary": "Update Metode Pembayaran",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment Method ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data Update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ybb-platform_payment-service_internal_domain_entities.PaymentMethodEntity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/github_com_ybb-platform_payment-service_internal_domain_entities.PaymentMethodEntity"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Menghapus (Soft Delete) metode pembayaran berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Methods"
                ],
                "summary": "Hapus Metode Pembayaran",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment Method ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payments/{id}/proof": {
            "post": {
                "description": "User mengupload foto bukti transfer untuk pembayaran manual",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manual Payment"
                ],
                "summary": "Upload Bukti Transfer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File Gambar Bukti Transfer (JPG/PNG)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payments/{id}/verify": {
            "post": {
                "description": "Admin menyetujui (Approve) atau menolak (Reject) pembayaran manual",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manual Payment"
                ],
                "summary": "Verifikasi Pembayaran (Admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data Verifikasi (Action \u0026 Admin ID)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_presentation_http_handlers.VerifyPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ybb-platform_payment-service_internal_domain_entities.PaymentMethodEntity": {
            "type": "object",
            "properties": {
                "account_name": {
                    "type": "string",
                    "example": "PT YBB Platform"
                },
                "account_number": {
                    "type": "string",
                    "example": "1234567890"
                },
                "admin_instructions": {
                    "type": "string",
                    "example": "Cek mutasi bank tanggal sekian"
                },
                "bank_name": {
                    "description": "--- Manual Payment Fields ---",
                    "type": "string",
                    "example": "BCA"
                },
                "code": {
                    "type": "string",
                    "example": "bca_manual"
                },
                "config": {
                    "description": "--- Configuration ---\nswaggertype digunakan agar Swagger tidak bingung membaca map[string]interface{}",
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "description": "--- Timestamps ---",
                    "type": "string",
                    "example": "2025-12-01T10:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Transfer manual ke rekening BCA"
                },
                "display_name": {
                    "type": "string",
                    "example": "Bank BCA"
                },
                "gateway_name": {
                    "description": "--- Automatic Payment Fields ---",
                    "type": "string",
                    "example": ""
                },
                "gateway_type": {
                    "type": "string",
                    "example": ""
                },
                "icon": {
                    "type": "string",
                    "example": "https://logo.com/bca.png"
                },
                "id": {
                    "description": "--- Primary Key ---",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "instructions": {
                    "type": "string",
                    "example": "Silakan transfer sesuai nominal unik"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "description": "--- Basic Info ---",
                    "type": "string",
                    "example": "Transfer Bank BCA"
                },
                "requires_proof": {
                    "type": "boolean",
                    "example": true
                },
                "sort_order": {
                    "type": "integer",
                    "example": 1
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_ybb-platform_payment-service_internal_domain_entities.PaymentMethodType"
                        }
                    ],
                    "example": "manual"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-12-01T10:00:00Z"
                }
            }
        },
        "github_com_ybb-platform_payment-service_internal_domain_entities.PaymentMethodType": {
            "type": "string",
            "enum": [
                "automatic",
                "manual"
            ],
            "x-enum-comments": {
                "MethodTypeAutomatic": "Via payment gateway",
                "MethodTypeManual": "Manual verification"
            },
            "x-enum-descriptions": [
                "Via payment gateway",
                "Manual verification"
            ],
            "x-enum-varnames": [
                "MethodTypeAutomatic",
                "MethodTypeManual"
            ]
        },
        "internal_presentation_http_handlers.VerifyPaymentRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "\"approve\" or \"reject\"",
                    "type": "string"
                },
                "admin_id": {
                    "description": "Simulated Admin ID",
                    "type": "string"
                },
                "reason": {
                    "description": "Required if rejected",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "YBB Payment Service API",
	Description:      "Ini adalah dokumentasi API untuk layanan pembayaran YBB Platform.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
