-- Seed: Create Sample Programs

INSERT INTO programs (
    id,
    title,
    description,
    type,
    status,
    start_date,
    end_date,
    application_deadline,
    location,
    capacity,
    fee,
    currency,
    requirements,
    benefits,
    created_by
) VALUES 
(
    uuid_generate_v4(),
    'YBB Global Summit 2026',
    'An international conference bringing together young leaders from around the world to discuss global challenges and innovative solutions.',
    'conference',
    'published',
    '2026-07-15 09:00:00',
    '2026-07-20 17:00:00',
    '2026-05-01 23:59:59',
    'Jakarta, Indonesia',
    500,
    250.00,
    'USD',
    '["Age 18-30", "English proficiency", "Valid passport"]',
    '["Networking opportunities", "Workshops and training", "Certificate of participation", "Accommodation included"]',
    (SELECT id FROM users WHERE email = 'admin@ybb-platform.com' LIMIT 1)
),
(
    uuid_generate_v4(),
    'Innovation Bootcamp',
    'A week-long intensive bootcamp focused on entrepreneurship, innovation, and startup development.',
    'bootcamp',
    'published',
    '2026-03-10 09:00:00',
    '2026-03-15 17:00:00',
    '2026-02-01 23:59:59',
    'Bali, Indonesia',
    50,
    500.00,
    'USD',
    '["Age 20-35", "Business or tech background preferred", "Laptop required"]',
    '["Mentorship from industry leaders", "Pitch competition", "Seed funding opportunity", "Meals and accommodation"]',
    (SELECT id FROM users WHERE email = 'admin@ybb-platform.com' LIMIT 1)
),
(
    uuid_generate_v4(),
    'Leadership Workshop Series',
    'A series of workshops designed to develop leadership skills and emotional intelligence.',
    'workshop',
    'published',
    '2026-02-01 14:00:00',
    '2026-02-01 18:00:00',
    '2026-01-25 23:59:59',
    'Virtual',
    200,
    50.00,
    'USD',
    '["Open to all ages", "Stable internet connection"]',
    '["Digital certificate", "Workshop materials", "Lifetime access to recordings"]',
    (SELECT id FROM users WHERE email = 'admin@ybb-platform.com' LIMIT 1)
) ON CONFLICT DO NOTHING;
