import { Injectable, ConflictException, NotFoundException, Inject } from '@nestjs/common';
import { IApplicationRepository } from '@core/interfaces/repositories/application.repository.interface';
import { ParticipantApplication, ApplicationStatus } from '@core/entities/participant-application.entity';
import { CreateApplicationCommand } from '../create-application.command';
import { ApplicationResponseDto } from '../../dto/application-response.dto';
import { ApplicationMapper } from '@modules/applications/infrastructure/mappers/application.mapper';
import { APPLICATION_REPOSITORY } from '@modules/applications/infrastructure/tokens';
import { MetricsService } from '@shared/infrastructure/monitoring/metrics.service';

/**
 * Create Application Handler
 * 
 * Application Layer - Command Handler
 * Handles business logic for creating applications
 */
@Injectable()
export class CreateApplicationHandler {
  constructor(
    @Inject(APPLICATION_REPOSITORY)
    private readonly applicationRepository: IApplicationRepository,
    private readonly applicationMapper: ApplicationMapper,
    private readonly metricsService: MetricsService,
  ) {}

  async execute(command: CreateApplicationCommand): Promise<ApplicationResponseDto> {
    // Check if application already exists
    const existing = await this.applicationRepository.findByParticipantAndProgram(
      command.participantId,
      command.programId,
    );

    if (existing) {
      throw new ConflictException(
        `Application already exists for participant ${command.participantId} in program ${command.programId}`,
      );
    }

    // Create application entity
    const application = new ParticipantApplication(
      null as any, // ID will be generated by database
      command.participantId,
      command.programId,
      ApplicationStatus.DRAFT,
      command.applicationCategory,
      {}, // personalData
      {}, // essayAnswers
      {}, // uploadedFiles
      command.motivationLetter,
      command.achievements,
      command.experiences,
      command.documents,
      command.requirementFiles,
      command.twibbonLink,
      command.pricingTierId,
    );

    // Save to database
    const saved = await this.applicationRepository.create(application);

    // Record metric
    this.metricsService.applicationStartedTotal.inc({ brand: command.applicationCategory });

    // Return DTO
    return this.applicationMapper.toDto(saved);
  }
}
