import { Injectable, ConflictException, NotFoundException, Inject } from '@nestjs/common';
import { IApplicationRepository } from '@core/interfaces/repositories/application.repository.interface';
import { ParticipantApplication, ApplicationStatus } from '@core/entities/participant-application.entity';
import { CreateApplicationCommand } from '../create-application.command';
import { ApplicationResponseDto } from '../../dto/application-response.dto';
import { ApplicationMapper } from '@modules/applications/infrastructure/mappers/application.mapper';
import { APPLICATION_REPOSITORY } from '@modules/applications/infrastructure/tokens';
import { MetricsService } from '@shared/infrastructure/monitoring/metrics.service';
import { CacheService } from '@shared/infrastructure/cache/cache.service';
import { PrismaService } from '@shared/infrastructure/prisma/prisma.service';
import { invalidateParticipantPortalCache } from '@shared/utils/invalidate-participant-portal-cache.util';

/**
 * Create Application Handler
 *
 * Application Layer - Command Handler
 * Handles business logic for creating applications
 */
@Injectable()
export class CreateApplicationHandler {
  constructor(
    @Inject(APPLICATION_REPOSITORY)
    private readonly applicationRepository: IApplicationRepository,
    private readonly applicationMapper: ApplicationMapper,
    private readonly metricsService: MetricsService,
    private readonly cacheService: CacheService,
    private readonly prisma: PrismaService,
  ) {}

  async execute(command: CreateApplicationCommand): Promise<ApplicationResponseDto> {
    // Check if application already exists
    const existing = await this.applicationRepository.findByParticipantAndProgram(
      command.participantId,
      command.programId,
    );

    if (existing) {
      throw new ConflictException(
        `Application already exists for participant ${command.participantId} in program ${command.programId}`,
      );
    }

    // Create application entity
    const application = new ParticipantApplication(
      '', // ID will be generated by database
      command.participantId,
      command.programId,
      ApplicationStatus.DRAFT,
      command.applicationCategory,
      {}, // personalData
      {}, // essayAnswers
      {}, // uploadedFiles
      command.motivationLetter,
      command.achievements,
      command.experiences,
      command.documents,
      command.requirementFiles,
      command.twibbonLink,
      command.pricingTierId,
    );

    // Save to database
    const saved = await this.applicationRepository.create(application);

    // Record metric
    this.metricsService.applicationStartedTotal.inc({ brand: command.applicationCategory });

    // Invalidate participant caches. This route is admin-only (POST
    // /applications), so the participant's actual users.id is never the JWT
    // principal — resolve it from the participant row rather than relying on
    // the (removed) @CacheInvalidate(['portal:*:${userId}']) decorator, which
    // resolved to the acting admin's own id (audit M103/M120). A newly
    // created application can already be reflected in a cached
    // portal:submissions list the participant loaded before this admin
    // action, so the portal cache — not just PARTICIPANT_LATEST_APP/STATS —
    // needs busting too.
    await invalidateParticipantPortalCache(this.prisma, this.cacheService, command.participantId);

    // Return DTO
    return this.applicationMapper.toDto(saved);
  }
}
