# services:
#   nginx:
#     ports:
#       - "8888:80" # Expose Nginx on port 8888 for local dev (avoiding 8080 conflict with Traefik)

services:

  postgres:
    ports:
      - "5432:5432"

  pgadmin:
    ports:
      - "5050:80" # Maps localhost:5050 to container:80

  minio:
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console

  rabbitmq:
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI

  file-service:
    ports:
      - "8001:8001"

  notification-service:
    ports:
      - "4002:4002"

  admin-dashboard:
    ports:
      - "4001:4001"

  grafana:
    ports:
      - "3001:3000" # Maps localhost:3001 to grafana:3000 (Next.js uses 3000)

  redis:
    ports:
      - "6379:6379"
