"""SQLAlchemy models for file metadata."""
# type: ignore
from sqlalchemy import Column, String, Integer, DateTime, Boolean, JSON, Text  # type: ignore
from sqlalchemy.sql import func  # type: ignore
from .database import Base


class FileModel(Base):
    """File metadata model."""
    
    __tablename__ = "files"
    
    id = Column(String(36), primary_key=True)
    filename = Column(String(255), nullable=False)
    original_filename = Column(String(255), nullable=False)
    file_type = Column(String(50), nullable=False)
    mime_type = Column(String(100), nullable=False)
    file_size = Column(Integer, nullable=False)
    storage_path = Column(String(500), nullable=False)
    bucket = Column(String(100), nullable=False)
    user_id = Column(String(36), nullable=False, index=True)
    brand_id = Column(String(50), nullable=False, index=True)
    
    # metadata = Column(JSON, nullable=True)
    file_metadata = Column("metadata", JSON, default={})

    uploaded_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    is_deleted = Column(Boolean, default=False, nullable=False)
    
    # Additional fields for documents
    document_type = Column(String(50), nullable=True)  # certificate, report, receipt, etc.
    generated = Column(Boolean, default=False)  # True if file was generated by system
    template_id = Column(String(36), nullable=True)  # Reference to template used
    version = Column(Integer, default=1)  # For versioning
    
    def __repr__(self):
        return f"<FileModel(id={self.id}, filename={self.filename}, user_id={self.user_id})>"
