-- Migration: Create files table for file service
-- Date: 2025-12-01
-- Description: Creates the files table to store file metadata with support for generated documents

-- Create files table
CREATE TABLE IF NOT EXISTS files (
    id VARCHAR(36) PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size INTEGER NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    bucket VARCHAR(100) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    brand_id VARCHAR(50) NOT NULL,
    metadata JSONB,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    
    -- Additional fields for generated documents
    document_type VARCHAR(50),  -- certificate, report, receipt, offer_letter, etc.
    generated BOOLEAN DEFAULT FALSE,  -- True if file was generated by system
    template_id VARCHAR(36),  -- Reference to template used
    version INTEGER DEFAULT 1  -- For versioning
);

-- Create indexes for better query performance
CREATE INDEX idx_files_user_id ON files(user_id);
CREATE INDEX idx_files_brand_id ON files(brand_id);
CREATE INDEX idx_files_bucket ON files(bucket);
CREATE INDEX idx_files_document_type ON files(document_type);
CREATE INDEX idx_files_uploaded_at ON files(uploaded_at DESC);
CREATE INDEX idx_files_user_brand ON files(user_id, brand_id) WHERE is_deleted = FALSE;

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_files_updated_at BEFORE UPDATE ON files
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Create certificate_verifications table for certificate verification
CREATE TABLE IF NOT EXISTS certificate_verifications (
    id SERIAL PRIMARY KEY,
    verification_hash VARCHAR(32) UNIQUE NOT NULL,
    file_id VARCHAR(36) REFERENCES files(id),
    participant_name VARCHAR(255) NOT NULL,
    program_name VARCHAR(255) NOT NULL,
    issue_date DATE NOT NULL,
    certificate_type VARCHAR(50) NOT NULL,  -- completion, participation
    verified_count INTEGER DEFAULT 0,  -- Track how many times verified
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_verified_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_cert_verification_hash ON certificate_verifications(verification_hash);
CREATE INDEX idx_cert_file_id ON certificate_verifications(file_id);

-- Comments
COMMENT ON TABLE files IS 'Stores metadata for all uploaded and generated files';
COMMENT ON COLUMN files.document_type IS 'Type of document: certificate, report, receipt, offer_letter, etc.';
COMMENT ON COLUMN files.generated IS 'Indicates if the file was generated by the system vs uploaded by user';
COMMENT ON COLUMN files.template_id IS 'Reference to the template used for generating the document';
COMMENT ON COLUMN files.version IS 'Version number for document versioning';

COMMENT ON TABLE certificate_verifications IS 'Stores certificate verification hashes for authenticity checking';
COMMENT ON COLUMN certificate_verifications.verification_hash IS 'Unique hash for certificate verification via QR code';
COMMENT ON COLUMN certificate_verifications.verified_count IS 'Number of times this certificate has been verified';
