export class Participant {
    id: string;
    userId: string;
    fullName: string;
    nickName?: string | null;
    displayName?: string | null;
    birthdate?: Date | null;
    gender?: string | null;
    phoneCountryCode?: string | null;
    phoneNumber?: string | null;
    phoneVerified?: boolean;
    nationality?: string | null;
    nationalityCode?: string | null;
    originCountry?: string | null;
    originCity?: string | null;
    originAddress?: string | null;
    currentCountry?: string | null;
    currentCity?: string | null;
    currentAddress?: string | null;
    educationLevel?: string | null;
    institution?: string | null;
    major?: string | null;
    graduationYear?: number | null;
    occupation?: string | null;
    instagramUsername?: string | null;
    linkedinUrl?: string | null;
    portfolioUrl?: string | null;
    organizations?: string | null;
    tshirtSize?: string | null;
    dietaryRestrictions?: string | null;
    medicalConditions?: string | null;
    specialNeeds?: string | null;
    emergencyContactName?: string | null;
    emergencyContactRelation?: string | null;
    emergencyContactCountryCode?: string | null;
    emergencyContactPhone?: string | null;
    emergencyContactEmail?: string | null;
    profilePictureUrl?: string | null;
    resumeUrl?: string | null;
    knowledgeSource?: string | null;
    referralCode?: string | null;
    preferences?: any | null;
    createdAt?: Date;
    updatedAt?: Date;
    profileCompletedAt?: Date | null;
    profileCompletionPercentage?: number;
    lastProfileUpdate?: Date | null;
}
