export type ProgramFormat = 'in_person' | 'hybrid' | 'online';

export class Program {
    constructor(
        public readonly id: string,
        public readonly brandId: string,
        public readonly name: string,
        public readonly slug: string,
        public readonly description: string | null,
        public readonly shortDescription: string | null,
        public readonly programType: string | null,
        public readonly programFormat: ProgramFormat | null,
        public readonly year: number,
        public readonly startDate: Date,
        public readonly endDate: Date,
        public readonly applicationDeadline: Date,
        public readonly location: string | null,
        public readonly capacity: number | null,
        public readonly isPublished: boolean,
        public readonly isVisibleToUsers: boolean,
        public readonly isActive: boolean,
        public readonly status: string,
        public readonly thumbnailUrl: string | null,
        public readonly bannerUrl: string | null,
        public readonly videoUrl: string | null,
        public readonly requireEmailVerification: boolean,
        public readonly currency: string,
        public readonly enableCurrencyConversion: boolean,
        public readonly usdInIdr: number | null,
        public readonly logoUrl: string | null,
        public readonly allowRegistration: boolean,
        public readonly registrationOpenDate: Date | null,
        public readonly registrationCloseDate: Date | null,
        public readonly requirePayment: boolean,
        public readonly registrationFee: number | null,
        public readonly requirementsDescription: string | null,
        public readonly benefitsDescription: string | null,
        public readonly termsAndConditions: string | null,
        public readonly essayGuidelineText: string | null,
        public readonly essayGuidelineUrl: string | null,
        public readonly previewChecklistItems: string[],
        public readonly metaTitle: string | null,
        public readonly metaDescription: string | null,
        public readonly createdAt: Date,
        public readonly updatedAt: Date,
        public readonly deletedAt: Date | null,
        public readonly brandName?: string | null,
        public readonly theme?: string | null,
    ) { }
}
