# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import file_service_pb2 as file__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in file_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.stream_unary(
                '/file.FileService/UploadFile',
                request_serializer=file__service__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=file__service__pb2.UploadFileResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/file.FileService/DownloadFile',
                request_serializer=file__service__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=file__service__pb2.DownloadFileResponse.FromString,
                _registered_method=True)
        self.GetFile = channel.unary_unary(
                '/file.FileService/GetFile',
                request_serializer=file__service__pb2.GetFileRequest.SerializeToString,
                response_deserializer=file__service__pb2.FileResponse.FromString,
                _registered_method=True)
        self.GenerateCertificate = channel.unary_unary(
                '/file.FileService/GenerateCertificate',
                request_serializer=file__service__pb2.GenerateCertificateRequest.SerializeToString,
                response_deserializer=file__service__pb2.GenerateDocumentResponse.FromString,
                _registered_method=True)
        self.GenerateReceipt = channel.unary_unary(
                '/file.FileService/GenerateReceipt',
                request_serializer=file__service__pb2.GenerateReceiptRequest.SerializeToString,
                response_deserializer=file__service__pb2.GenerateDocumentResponse.FromString,
                _registered_method=True)
        self.GetPresignedUploadUrl = channel.unary_unary(
                '/file.FileService/GetPresignedUploadUrl',
                request_serializer=file__service__pb2.GetPresignedUploadUrlRequest.SerializeToString,
                response_deserializer=file__service__pb2.GetPresignedUploadUrlResponse.FromString,
                _registered_method=True)
        self.ConfirmUpload = channel.unary_unary(
                '/file.FileService/ConfirmUpload',
                request_serializer=file__service__pb2.ConfirmUploadRequest.SerializeToString,
                response_deserializer=file__service__pb2.ConfirmUploadResponse.FromString,
                _registered_method=True)
        self.GetPresignedUrlInternal = channel.unary_unary(
                '/file.FileService/GetPresignedUrlInternal',
                request_serializer=file__service__pb2.GetPresignedUrlInternalRequest.SerializeToString,
                response_deserializer=file__service__pb2.GetPresignedUrlInternalResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request_iterator, context):
        """Upload a file (streaming request to handle large files)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Download a file (streaming response)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Get file metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCertificate(self, request, context):
        """--- New Methods ---

        Generate a certificate (returns PDF bytes)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReceipt(self, request, context):
        """Generate a receipt (returns PDF bytes)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPresignedUploadUrl(self, request, context):
        """Get a presigned URL for direct upload (Client -> S3/MinIO)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmUpload(self, request, context):
        """Confirm that a file has been uploaded (Event Hook)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPresignedUrlInternal(self, request, context):
        """Internal-only: mint a fresh presigned GET URL for a private file, without the
        per-user ownership check (the caller has already run its own eligibility check).
        Scoped to an allowlist of private categories (documents, signed-copies).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=file__service__pb2.UploadFileRequest.FromString,
                    response_serializer=file__service__pb2.UploadFileResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=file__service__pb2.DownloadFileRequest.FromString,
                    response_serializer=file__service__pb2.DownloadFileResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=file__service__pb2.GetFileRequest.FromString,
                    response_serializer=file__service__pb2.FileResponse.SerializeToString,
            ),
            'GenerateCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCertificate,
                    request_deserializer=file__service__pb2.GenerateCertificateRequest.FromString,
                    response_serializer=file__service__pb2.GenerateDocumentResponse.SerializeToString,
            ),
            'GenerateReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReceipt,
                    request_deserializer=file__service__pb2.GenerateReceiptRequest.FromString,
                    response_serializer=file__service__pb2.GenerateDocumentResponse.SerializeToString,
            ),
            'GetPresignedUploadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPresignedUploadUrl,
                    request_deserializer=file__service__pb2.GetPresignedUploadUrlRequest.FromString,
                    response_serializer=file__service__pb2.GetPresignedUploadUrlResponse.SerializeToString,
            ),
            'ConfirmUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmUpload,
                    request_deserializer=file__service__pb2.ConfirmUploadRequest.FromString,
                    response_serializer=file__service__pb2.ConfirmUploadResponse.SerializeToString,
            ),
            'GetPresignedUrlInternal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPresignedUrlInternal,
                    request_deserializer=file__service__pb2.GetPresignedUrlInternalRequest.FromString,
                    response_serializer=file__service__pb2.GetPresignedUrlInternalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('file.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/file.FileService/UploadFile',
            file__service__pb2.UploadFileRequest.SerializeToString,
            file__service__pb2.UploadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/file.FileService/DownloadFile',
            file__service__pb2.DownloadFileRequest.SerializeToString,
            file__service__pb2.DownloadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.FileService/GetFile',
            file__service__pb2.GetFileRequest.SerializeToString,
            file__service__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.FileService/GenerateCertificate',
            file__service__pb2.GenerateCertificateRequest.SerializeToString,
            file__service__pb2.GenerateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.FileService/GenerateReceipt',
            file__service__pb2.GenerateReceiptRequest.SerializeToString,
            file__service__pb2.GenerateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPresignedUploadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.FileService/GetPresignedUploadUrl',
            file__service__pb2.GetPresignedUploadUrlRequest.SerializeToString,
            file__service__pb2.GetPresignedUploadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.FileService/ConfirmUpload',
            file__service__pb2.ConfirmUploadRequest.SerializeToString,
            file__service__pb2.ConfirmUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPresignedUrlInternal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.FileService/GetPresignedUrlInternal',
            file__service__pb2.GetPresignedUrlInternalRequest.SerializeToString,
            file__service__pb2.GetPresignedUrlInternalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
