apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Postgres - API
    type: postgres
    uid: postgres-api
    url: ${DB_HOST_API}:${DB_PORT_API}
    database: ${DB_NAME_API}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
    isDefault: false
    editable: true

  - name: Postgres - Payment
    type: postgres
    uid: postgres-payment
    url: ${DB_HOST_PAYMENT}:${DB_PORT_PAYMENT}
    database: ${DB_NAME_API} # Assuming same DB name for now, or use separate var
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
    isDefault: false
    editable: true

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      timeout: 60
      maxLines: 1000
    isDefault: false
    editable: false

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: false
      lokiSearch:
        datasourceUid: 'loki'
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{job="ybb-api"} |= "$${__span.traceId}"'
    isDefault: false
    editable: false
