// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: payment_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProgramId     string                 `protobuf:"bytes,4,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	FromDate      string                 `protobuf:"bytes,6,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,7,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPaymentsRequest) Reset() {
	*x = AdminListPaymentsRequest{}
	mi := &file_payment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPaymentsRequest) ProtoMessage() {}

func (x *AdminListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*AdminListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{0}
}

func (x *AdminListPaymentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListPaymentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AdminListPaymentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminListPaymentsRequest) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *AdminListPaymentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminListPaymentsRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *AdminListPaymentsRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type AdminListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*PaymentIntent       `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPaymentsResponse) Reset() {
	*x = AdminListPaymentsResponse{}
	mi := &file_payment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPaymentsResponse) ProtoMessage() {}

func (x *AdminListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*AdminListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{1}
}

func (x *AdminListPaymentsResponse) GetPayments() []*PaymentIntent {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *AdminListPaymentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AdminListPaymentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListPaymentsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetIntentsByReferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceType string                 `protobuf:"bytes,1,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,2,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntentsByReferenceRequest) Reset() {
	*x = GetIntentsByReferenceRequest{}
	mi := &file_payment_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntentsByReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntentsByReferenceRequest) ProtoMessage() {}

func (x *GetIntentsByReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntentsByReferenceRequest.ProtoReflect.Descriptor instead.
func (*GetIntentsByReferenceRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetIntentsByReferenceRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *GetIntentsByReferenceRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type PaymentIntent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReferenceType string                 `protobuf:"bytes,7,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,8,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Snapshots of customer/item details
	CustomerName  string        `protobuf:"bytes,10,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerEmail string        `protobuf:"bytes,11,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	CustomerPhone string        `protobuf:"bytes,12,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	Description   string        `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	ItemDetails   []*ItemDetail `protobuf:"bytes,14,rep,name=item_details,json=itemDetails,proto3" json:"item_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentIntent) Reset() {
	*x = PaymentIntent{}
	mi := &file_payment_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentIntent) ProtoMessage() {}

func (x *PaymentIntent) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentIntent.ProtoReflect.Descriptor instead.
func (*PaymentIntent) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentIntent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentIntent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentIntent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentIntent) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentIntent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentIntent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentIntent) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *PaymentIntent) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *PaymentIntent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PaymentIntent) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *PaymentIntent) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *PaymentIntent) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *PaymentIntent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PaymentIntent) GetItemDetails() []*ItemDetail {
	if x != nil {
		return x.ItemDetails
	}
	return nil
}

type ItemDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Brand         string                 `protobuf:"bytes,5,opt,name=brand,proto3" json:"brand,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	MerchantName  string                 `protobuf:"bytes,7,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDetail) Reset() {
	*x = ItemDetail{}
	mi := &file_payment_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDetail) ProtoMessage() {}

func (x *ItemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDetail.ProtoReflect.Descriptor instead.
func (*ItemDetail) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{4}
}

func (x *ItemDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemDetail) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemDetail) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemDetail) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ItemDetail) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ItemDetail) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

type GetIntentsByReferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intents       []*PaymentIntent       `protobuf:"bytes,1,rep,name=intents,proto3" json:"intents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntentsByReferenceResponse) Reset() {
	*x = GetIntentsByReferenceResponse{}
	mi := &file_payment_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntentsByReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntentsByReferenceResponse) ProtoMessage() {}

func (x *GetIntentsByReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntentsByReferenceResponse.ProtoReflect.Descriptor instead.
func (*GetIntentsByReferenceResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetIntentsByReferenceResponse) GetIntents() []*PaymentIntent {
	if x != nil {
		return x.Intents
	}
	return nil
}

type CreateIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"` // Optional
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	ReferenceType string                 `protobuf:"bytes,5,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,6,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Customer Info
	CustomerName  string `protobuf:"bytes,8,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerEmail string `protobuf:"bytes,9,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	CustomerPhone string `protobuf:"bytes,10,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	// Item Details
	Description  string        `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	ItemDetails  []*ItemDetail `protobuf:"bytes,12,rep,name=item_details,json=itemDetails,proto3" json:"item_details,omitempty"`
	// Exchange rate snapshot (USD to IDR at the time of intent creation)
	ExchangeRate  float64 `protobuf:"fixed64,13,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIntentRequest) Reset() {
	*x = CreateIntentRequest{}
	mi := &file_payment_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntentRequest) ProtoMessage() {}

func (x *CreateIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntentRequest.ProtoReflect.Descriptor instead.
func (*CreateIntentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateIntentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateIntentRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *CreateIntentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateIntentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateIntentRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *CreateIntentRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *CreateIntentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateIntentRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *CreateIntentRequest) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *CreateIntentRequest) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *CreateIntentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIntentRequest) GetItemDetails() []*ItemDetail {
	if x != nil {
		return x.ItemDetails
	}
	return nil
}

func (x *CreateIntentRequest) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

type CreateIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"` // Might be needed for some gateways, or empty
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIntentResponse) Reset() {
	*x = CreateIntentResponse{}
	mi := &file_payment_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntentResponse) ProtoMessage() {}

func (x *CreateIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntentResponse.ProtoReflect.Descriptor instead.
func (*CreateIntentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateIntentResponse) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *CreateIntentResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CreateIntentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubmitManualPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	ProofFileId   string                 `protobuf:"bytes,2,opt,name=proof_file_id,json=proofFileId,proto3" json:"proof_file_id,omitempty"` // optional if just using URL
	ProofFileUrl  string                 `protobuf:"bytes,3,opt,name=proof_file_url,json=proofFileUrl,proto3" json:"proof_file_url,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"` // notes from user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitManualPaymentRequest) Reset() {
	*x = SubmitManualPaymentRequest{}
	mi := &file_payment_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitManualPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitManualPaymentRequest) ProtoMessage() {}

func (x *SubmitManualPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitManualPaymentRequest.ProtoReflect.Descriptor instead.
func (*SubmitManualPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitManualPaymentRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetProofFileId() string {
	if x != nil {
		return x.ProofFileId
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetProofFileUrl() string {
	if x != nil {
		return x.ProofFileUrl
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type SubmitManualPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "PENDING_REVIEW"
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitManualPaymentResponse) Reset() {
	*x = SubmitManualPaymentResponse{}
	mi := &file_payment_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitManualPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitManualPaymentResponse) ProtoMessage() {}

func (x *SubmitManualPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitManualPaymentResponse.ProtoReflect.Descriptor instead.
func (*SubmitManualPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitManualPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitManualPaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type VerifyManualPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "SUCCESS", "FAILED"
	AdminId       string                 `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyManualPaymentRequest) Reset() {
	*x = VerifyManualPaymentRequest{}
	mi := &file_payment_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyManualPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyManualPaymentRequest) ProtoMessage() {}

func (x *VerifyManualPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyManualPaymentRequest.ProtoReflect.Descriptor instead.
func (*VerifyManualPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyManualPaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VerifyManualPaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VerifyManualPaymentRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *VerifyManualPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type VerifyManualPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyManualPaymentResponse) Reset() {
	*x = VerifyManualPaymentResponse{}
	mi := &file_payment_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyManualPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyManualPaymentResponse) ProtoMessage() {}

func (x *VerifyManualPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyManualPaymentResponse.ProtoReflect.Descriptor instead.
func (*VerifyManualPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyManualPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetPaymentMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodsRequest) Reset() {
	*x = GetPaymentMethodsRequest{}
	mi := &file_payment_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodsRequest) ProtoMessage() {}

func (x *GetPaymentMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodsRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetPaymentMethodsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetPaymentMethodsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PaymentMethod struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"` // e.g., "bank_transfer", "credit_card", "ewallet"
	ImageUrl string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// Fee details for user display
	EstimatedFee  float64 `protobuf:"fixed64,5,opt,name=estimated_fee,json=estimatedFee,proto3" json:"estimated_fee,omitempty"`
	IsSurcharge   bool    `protobuf:"varint,6,opt,name=is_surcharge,json=isSurcharge,proto3" json:"is_surcharge,omitempty"` // If true, UI should show "Fee: X" and "Total: Amount + Fee"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_payment_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{13}
}

func (x *PaymentMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentMethod) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PaymentMethod) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *PaymentMethod) GetEstimatedFee() float64 {
	if x != nil {
		return x.EstimatedFee
	}
	return 0
}

func (x *PaymentMethod) GetIsSurcharge() bool {
	if x != nil {
		return x.IsSurcharge
	}
	return false
}

type GetPaymentMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []*PaymentMethod       `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodsResponse) Reset() {
	*x = GetPaymentMethodsResponse{}
	mi := &file_payment_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodsResponse) ProtoMessage() {}

func (x *GetPaymentMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodsResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetPaymentMethodsResponse) GetMethods() []*PaymentMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

type PaymentDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arbitrary JSON string for gateway specific details
	DetailsJson   string `protobuf:"bytes,1,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentDetails) Reset() {
	*x = PaymentDetails{}
	mi := &file_payment_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentDetails) ProtoMessage() {}

func (x *PaymentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentDetails.ProtoReflect.Descriptor instead.
func (*PaymentDetails) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{15}
}

func (x *PaymentDetails) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

type ProcessPaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntentId        string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,2,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	GatewayToken    string                 `protobuf:"bytes,3,opt,name=gateway_token,json=gatewayToken,proto3" json:"gateway_token,omitempty"` // Token from Midtrans/Xendit JS SDK
	PaymentDetails  *PaymentDetails        `protobuf:"bytes,4,opt,name=payment_details,json=paymentDetails,proto3" json:"payment_details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_payment_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{16}
}

func (x *ProcessPaymentRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetGatewayToken() string {
	if x != nil {
		return x.GatewayToken
	}
	return ""
}

func (x *ProcessPaymentRequest) GetPaymentDetails() *PaymentDetails {
	if x != nil {
		return x.PaymentDetails
	}
	return nil
}

type ProcessPaymentAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "redirect", "display_qr", "none"
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	QrString      string                 `protobuf:"bytes,3,opt,name=qr_string,json=qrString,proto3" json:"qr_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentAction) Reset() {
	*x = ProcessPaymentAction{}
	mi := &file_payment_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentAction) ProtoMessage() {}

func (x *ProcessPaymentAction) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentAction.ProtoReflect.Descriptor instead.
func (*ProcessPaymentAction) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{17}
}

func (x *ProcessPaymentAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProcessPaymentAction) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProcessPaymentAction) GetQrString() string {
	if x != nil {
		return x.QrString
	}
	return ""
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "PENDING", "SUCCESS", "FAILED"
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Action        *ProcessPaymentAction  `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_payment_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{18}
}

func (x *ProcessPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessPaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ProcessPaymentResponse) GetAction() *ProcessPaymentAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ProcessPaymentResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FeeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FixedFee      float64                `protobuf:"fixed64,1,opt,name=fixed_fee,json=fixedFee,proto3" json:"fixed_fee,omitempty"`
	PercentageFee float64                `protobuf:"fixed64,2,opt,name=percentage_fee,json=percentageFee,proto3" json:"percentage_fee,omitempty"`
	MinFee        float64                `protobuf:"fixed64,3,opt,name=min_fee,json=minFee,proto3" json:"min_fee,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	IsSurcharge   bool                   `protobuf:"varint,5,opt,name=is_surcharge,json=isSurcharge,proto3" json:"is_surcharge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeConfig) Reset() {
	*x = FeeConfig{}
	mi := &file_payment_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeConfig) ProtoMessage() {}

func (x *FeeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeConfig.ProtoReflect.Descriptor instead.
func (*FeeConfig) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{19}
}

func (x *FeeConfig) GetFixedFee() float64 {
	if x != nil {
		return x.FixedFee
	}
	return 0
}

func (x *FeeConfig) GetPercentageFee() float64 {
	if x != nil {
		return x.PercentageFee
	}
	return 0
}

func (x *FeeConfig) GetMinFee() float64 {
	if x != nil {
		return x.MinFee
	}
	return 0
}

func (x *FeeConfig) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FeeConfig) GetIsSurcharge() bool {
	if x != nil {
		return x.IsSurcharge
	}
	return false
}

type AdminPaymentMethod struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Internal name
	Type        string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "automatic", "manual"
	Code        string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"` // "bca_va"
	IsActive    bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DisplayName string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Icon        string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	GatewayName string                 `protobuf:"bytes,9,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`  // "midtrans"
	GatewayType string                 `protobuf:"bytes,10,opt,name=gateway_type,json=gatewayType,proto3" json:"gateway_type,omitempty"` // "bank_transfer"
	// Manual fields
	BankName          string     `protobuf:"bytes,11,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	AccountNumber     string     `protobuf:"bytes,12,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountName       string     `protobuf:"bytes,13,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Instructions      string     `protobuf:"bytes,14,opt,name=instructions,proto3" json:"instructions,omitempty"`
	RequiresProof     bool       `protobuf:"varint,15,opt,name=requires_proof,json=requiresProof,proto3" json:"requires_proof,omitempty"`
	AdminInstructions string     `protobuf:"bytes,16,opt,name=admin_instructions,json=adminInstructions,proto3" json:"admin_instructions,omitempty"`
	Config            *FeeConfig `protobuf:"bytes,17,opt,name=config,proto3" json:"config,omitempty"`
	SortOrder         int32      `protobuf:"varint,18,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminPaymentMethod) Reset() {
	*x = AdminPaymentMethod{}
	mi := &file_payment_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPaymentMethod) ProtoMessage() {}

func (x *AdminPaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPaymentMethod.ProtoReflect.Descriptor instead.
func (*AdminPaymentMethod) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{20}
}

func (x *AdminPaymentMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminPaymentMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminPaymentMethod) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AdminPaymentMethod) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AdminPaymentMethod) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AdminPaymentMethod) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AdminPaymentMethod) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminPaymentMethod) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AdminPaymentMethod) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *AdminPaymentMethod) GetGatewayType() string {
	if x != nil {
		return x.GatewayType
	}
	return ""
}

func (x *AdminPaymentMethod) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *AdminPaymentMethod) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AdminPaymentMethod) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AdminPaymentMethod) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *AdminPaymentMethod) GetRequiresProof() bool {
	if x != nil {
		return x.RequiresProof
	}
	return false
}

func (x *AdminPaymentMethod) GetAdminInstructions() string {
	if x != nil {
		return x.AdminInstructions
	}
	return ""
}

func (x *AdminPaymentMethod) GetConfig() *FeeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AdminPaymentMethod) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type AdminCreatePaymentMethodRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type              string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Code              string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	IsActive          bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DisplayName       string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description       string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Icon              string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	GatewayName       string                 `protobuf:"bytes,8,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	GatewayType       string                 `protobuf:"bytes,9,opt,name=gateway_type,json=gatewayType,proto3" json:"gateway_type,omitempty"`
	BankName          string                 `protobuf:"bytes,10,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,11,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountName       string                 `protobuf:"bytes,12,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Instructions      string                 `protobuf:"bytes,13,opt,name=instructions,proto3" json:"instructions,omitempty"`
	RequiresProof     bool                   `protobuf:"varint,14,opt,name=requires_proof,json=requiresProof,proto3" json:"requires_proof,omitempty"`
	AdminInstructions string                 `protobuf:"bytes,15,opt,name=admin_instructions,json=adminInstructions,proto3" json:"admin_instructions,omitempty"`
	Config            *FeeConfig             `protobuf:"bytes,16,opt,name=config,proto3" json:"config,omitempty"`
	SortOrder         int32                  `protobuf:"varint,17,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminCreatePaymentMethodRequest) Reset() {
	*x = AdminCreatePaymentMethodRequest{}
	mi := &file_payment_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCreatePaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreatePaymentMethodRequest) ProtoMessage() {}

func (x *AdminCreatePaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreatePaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*AdminCreatePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{21}
}

func (x *AdminCreatePaymentMethodRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AdminCreatePaymentMethodRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetGatewayType() string {
	if x != nil {
		return x.GatewayType
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetRequiresProof() bool {
	if x != nil {
		return x.RequiresProof
	}
	return false
}

func (x *AdminCreatePaymentMethodRequest) GetAdminInstructions() string {
	if x != nil {
		return x.AdminInstructions
	}
	return ""
}

func (x *AdminCreatePaymentMethodRequest) GetConfig() *FeeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AdminCreatePaymentMethodRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type AdminCreatePaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCreatePaymentMethodResponse) Reset() {
	*x = AdminCreatePaymentMethodResponse{}
	mi := &file_payment_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCreatePaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreatePaymentMethodResponse) ProtoMessage() {}

func (x *AdminCreatePaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreatePaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*AdminCreatePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{22}
}

func (x *AdminCreatePaymentMethodResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AdminUpdatePaymentMethodRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type              string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Code              string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	IsActive          bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DisplayName       string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description       string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Icon              string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	GatewayName       string                 `protobuf:"bytes,9,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	GatewayType       string                 `protobuf:"bytes,10,opt,name=gateway_type,json=gatewayType,proto3" json:"gateway_type,omitempty"`
	BankName          string                 `protobuf:"bytes,11,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	AccountNumber     string                 `protobuf:"bytes,12,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountName       string                 `protobuf:"bytes,13,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Instructions      string                 `protobuf:"bytes,14,opt,name=instructions,proto3" json:"instructions,omitempty"`
	RequiresProof     bool                   `protobuf:"varint,15,opt,name=requires_proof,json=requiresProof,proto3" json:"requires_proof,omitempty"`
	AdminInstructions string                 `protobuf:"bytes,16,opt,name=admin_instructions,json=adminInstructions,proto3" json:"admin_instructions,omitempty"`
	Config            *FeeConfig             `protobuf:"bytes,17,opt,name=config,proto3" json:"config,omitempty"`
	SortOrder         int32                  `protobuf:"varint,18,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminUpdatePaymentMethodRequest) Reset() {
	*x = AdminUpdatePaymentMethodRequest{}
	mi := &file_payment_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdatePaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdatePaymentMethodRequest) ProtoMessage() {}

func (x *AdminUpdatePaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdatePaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdatePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{23}
}

func (x *AdminUpdatePaymentMethodRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AdminUpdatePaymentMethodRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetGatewayType() string {
	if x != nil {
		return x.GatewayType
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetRequiresProof() bool {
	if x != nil {
		return x.RequiresProof
	}
	return false
}

func (x *AdminUpdatePaymentMethodRequest) GetAdminInstructions() string {
	if x != nil {
		return x.AdminInstructions
	}
	return ""
}

func (x *AdminUpdatePaymentMethodRequest) GetConfig() *FeeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AdminUpdatePaymentMethodRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type AdminUpdatePaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdatePaymentMethodResponse) Reset() {
	*x = AdminUpdatePaymentMethodResponse{}
	mi := &file_payment_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdatePaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdatePaymentMethodResponse) ProtoMessage() {}

func (x *AdminUpdatePaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdatePaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*AdminUpdatePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{24}
}

func (x *AdminUpdatePaymentMethodResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AdminDeletePaymentMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeletePaymentMethodRequest) Reset() {
	*x = AdminDeletePaymentMethodRequest{}
	mi := &file_payment_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeletePaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeletePaymentMethodRequest) ProtoMessage() {}

func (x *AdminDeletePaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeletePaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*AdminDeletePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{25}
}

func (x *AdminDeletePaymentMethodRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AdminDeletePaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeletePaymentMethodResponse) Reset() {
	*x = AdminDeletePaymentMethodResponse{}
	mi := &file_payment_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeletePaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeletePaymentMethodResponse) ProtoMessage() {}

func (x *AdminDeletePaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeletePaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*AdminDeletePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{26}
}

func (x *AdminDeletePaymentMethodResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AdminGetPaymentMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetPaymentMethodRequest) Reset() {
	*x = AdminGetPaymentMethodRequest{}
	mi := &file_payment_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetPaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetPaymentMethodRequest) ProtoMessage() {}

func (x *AdminGetPaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetPaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*AdminGetPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{27}
}

func (x *AdminGetPaymentMethodRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AdminGetPaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        *AdminPaymentMethod    `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetPaymentMethodResponse) Reset() {
	*x = AdminGetPaymentMethodResponse{}
	mi := &file_payment_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetPaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetPaymentMethodResponse) ProtoMessage() {}

func (x *AdminGetPaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetPaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*AdminGetPaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{28}
}

func (x *AdminGetPaymentMethodResponse) GetMethod() *AdminPaymentMethod {
	if x != nil {
		return x.Method
	}
	return nil
}

type AdminListPaymentMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPaymentMethodsRequest) Reset() {
	*x = AdminListPaymentMethodsRequest{}
	mi := &file_payment_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPaymentMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPaymentMethodsRequest) ProtoMessage() {}

func (x *AdminListPaymentMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPaymentMethodsRequest.ProtoReflect.Descriptor instead.
func (*AdminListPaymentMethodsRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{29}
}

type AdminListPaymentMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []*AdminPaymentMethod  `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPaymentMethodsResponse) Reset() {
	*x = AdminListPaymentMethodsResponse{}
	mi := &file_payment_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPaymentMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPaymentMethodsResponse) ProtoMessage() {}

func (x *AdminListPaymentMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPaymentMethodsResponse.ProtoReflect.Descriptor instead.
func (*AdminListPaymentMethodsResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{30}
}

func (x *AdminListPaymentMethodsResponse) GetMethods() []*AdminPaymentMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

var File_payment_service_proto protoreflect.FileDescriptor

const file_payment_service_proto_rawDesc = "" +
	"\n" +
	"\x15payment_service.proto\x12\apayment\"\xca\x01\n" +
	"\x18AdminListPaymentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"program_id\x18\x04 \x01(\tR\tprogramId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tfrom_date\x18\x06 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\a \x01(\tR\x06toDate\"\x9a\x01\n" +
	"\x19AdminListPaymentsResponse\x122\n" +
	"\bpayments\x18\x01 \x03(\v2\x16.payment.PaymentIntentR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"h\n" +
	"\x1cGetIntentsByReferenceRequest\x12%\n" +
	"\x0ereference_type\x18\x01 \x01(\tR\rreferenceType\x12!\n" +
	"\freference_id\x18\x02 \x01(\tR\vreferenceId\"\xb9\x04\n" +
	"\rPaymentIntent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12%\n" +
	"\x0ereference_type\x18\a \x01(\tR\rreferenceType\x12!\n" +
	"\freference_id\x18\b \x01(\tR\vreferenceId\x12@\n" +
	"\bmetadata\x18\t \x03(\v2$.payment.PaymentIntent.MetadataEntryR\bmetadata\x12#\n" +
	"\rcustomer_name\x18\n" +
	" \x01(\tR\fcustomerName\x12%\n" +
	"\x0ecustomer_email\x18\v \x01(\tR\rcustomerEmail\x12%\n" +
	"\x0ecustomer_phone\x18\f \x01(\tR\rcustomerPhone\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x126\n" +
	"\fitem_details\x18\x0e \x03(\v2\x13.payment.ItemDetailR\vitemDetails\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\n" +
	"ItemDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05brand\x18\x05 \x01(\tR\x05brand\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12#\n" +
	"\rmerchant_name\x18\a \x01(\tR\fmerchantName\"Q\n" +
	"\x1dGetIntentsByReferenceResponse\x120\n" +
	"\aintents\x18\x01 \x03(\v2\x16.payment.PaymentIntentR\aintents\"\xa5\x04\n" +
	"\x13CreateIntentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12%\n" +
	"\x0ereference_type\x18\x05 \x01(\tR\rreferenceType\x12!\n" +
	"\freference_id\x18\x06 \x01(\tR\vreferenceId\x12F\n" +
	"\bmetadata\x18\a \x03(\v2*.payment.CreateIntentRequest.MetadataEntryR\bmetadata\x12#\n" +
	"\rcustomer_name\x18\b \x01(\tR\fcustomerName\x12%\n" +
	"\x0ecustomer_email\x18\t \x01(\tR\rcustomerEmail\x12%\n" +
	"\x0ecustomer_phone\x18\n" +
	" \x01(\tR\rcustomerPhone\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x126\n" +
	"\fitem_details\x18\f \x03(\v2\x13.payment.ItemDetailR\vitemDetails\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x14CreateIntentResponse\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x9d\x01\n" +
	"\x1aSubmitManualPaymentRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12\"\n" +
	"\rproof_file_id\x18\x02 \x01(\tR\vproofFileId\x12$\n" +
	"\x0eproof_file_url\x18\x03 \x01(\tR\fproofFileUrl\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\"\\\n" +
	"\x1bSubmitManualPaymentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"\x8e\x01\n" +
	"\x1aVerifyManualPaymentRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\tR\aadminId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"5\n" +
	"\x1bVerifyManualPaymentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"N\n" +
	"\x18GetPaymentMethodsRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xb4\x01\n" +
	"\rPaymentMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12#\n" +
	"\restimated_fee\x18\x05 \x01(\x01R\festimatedFee\x12!\n" +
	"\fis_surcharge\x18\x06 \x01(\bR\visSurcharge\"M\n" +
	"\x19GetPaymentMethodsResponse\x120\n" +
	"\amethods\x18\x01 \x03(\v2\x16.payment.PaymentMethodR\amethods\"3\n" +
	"\x0ePaymentDetails\x12!\n" +
	"\fdetails_json\x18\x01 \x01(\tR\vdetailsJson\"\xc7\x01\n" +
	"\x15ProcessPaymentRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12*\n" +
	"\x11payment_method_id\x18\x02 \x01(\tR\x0fpaymentMethodId\x12#\n" +
	"\rgateway_token\x18\x03 \x01(\tR\fgatewayToken\x12@\n" +
	"\x0fpayment_details\x18\x04 \x01(\v2\x17.payment.PaymentDetailsR\x0epaymentDetails\"Y\n" +
	"\x14ProcessPaymentAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1b\n" +
	"\tqr_string\x18\x03 \x01(\tR\bqrString\"\x96\x02\n" +
	"\x16ProcessPaymentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x125\n" +
	"\x06action\x18\x03 \x01(\v2\x1d.payment.ProcessPaymentActionR\x06action\x12I\n" +
	"\bmetadata\x18\x04 \x03(\v2-.payment.ProcessPaymentResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\tFeeConfig\x12\x1b\n" +
	"\tfixed_fee\x18\x01 \x01(\x01R\bfixedFee\x12%\n" +
	"\x0epercentage_fee\x18\x02 \x01(\x01R\rpercentageFee\x12\x17\n" +
	"\amin_fee\x18\x03 \x01(\x01R\x06minFee\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12!\n" +
	"\fis_surcharge\x18\x05 \x01(\bR\visSurcharge\"\xc8\x04\n" +
	"\x12AdminPaymentMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12!\n" +
	"\fgateway_name\x18\t \x01(\tR\vgatewayName\x12!\n" +
	"\fgateway_type\x18\n" +
	" \x01(\tR\vgatewayType\x12\x1b\n" +
	"\tbank_name\x18\v \x01(\tR\bbankName\x12%\n" +
	"\x0eaccount_number\x18\f \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_name\x18\r \x01(\tR\vaccountName\x12\"\n" +
	"\finstructions\x18\x0e \x01(\tR\finstructions\x12%\n" +
	"\x0erequires_proof\x18\x0f \x01(\bR\rrequiresProof\x12-\n" +
	"\x12admin_instructions\x18\x10 \x01(\tR\x11adminInstructions\x12*\n" +
	"\x06config\x18\x11 \x01(\v2\x12.payment.FeeConfigR\x06config\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x12 \x01(\x05R\tsortOrder\"\xc5\x04\n" +
	"\x1fAdminCreatePaymentMethodRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12!\n" +
	"\fgateway_name\x18\b \x01(\tR\vgatewayName\x12!\n" +
	"\fgateway_type\x18\t \x01(\tR\vgatewayType\x12\x1b\n" +
	"\tbank_name\x18\n" +
	" \x01(\tR\bbankName\x12%\n" +
	"\x0eaccount_number\x18\v \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_name\x18\f \x01(\tR\vaccountName\x12\"\n" +
	"\finstructions\x18\r \x01(\tR\finstructions\x12%\n" +
	"\x0erequires_proof\x18\x0e \x01(\bR\rrequiresProof\x12-\n" +
	"\x12admin_instructions\x18\x0f \x01(\tR\x11adminInstructions\x12*\n" +
	"\x06config\x18\x10 \x01(\v2\x12.payment.FeeConfigR\x06config\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x11 \x01(\x05R\tsortOrder\"2\n" +
	" AdminCreatePaymentMethodResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd5\x04\n" +
	"\x1fAdminUpdatePaymentMethodRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12!\n" +
	"\fgateway_name\x18\t \x01(\tR\vgatewayName\x12!\n" +
	"\fgateway_type\x18\n" +
	" \x01(\tR\vgatewayType\x12\x1b\n" +
	"\tbank_name\x18\v \x01(\tR\bbankName\x12%\n" +
	"\x0eaccount_number\x18\f \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_name\x18\r \x01(\tR\vaccountName\x12\"\n" +
	"\finstructions\x18\x0e \x01(\tR\finstructions\x12%\n" +
	"\x0erequires_proof\x18\x0f \x01(\bR\rrequiresProof\x12-\n" +
	"\x12admin_instructions\x18\x10 \x01(\tR\x11adminInstructions\x12*\n" +
	"\x06config\x18\x11 \x01(\v2\x12.payment.FeeConfigR\x06config\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x12 \x01(\x05R\tsortOrder\"2\n" +
	" AdminUpdatePaymentMethodResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x1fAdminDeletePaymentMethodRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	" AdminDeletePaymentMethodResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x1cAdminGetPaymentMethodRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x1dAdminGetPaymentMethodResponse\x123\n" +
	"\x06method\x18\x01 \x01(\v2\x1b.payment.AdminPaymentMethodR\x06method\" \n" +
	"\x1eAdminListPaymentMethodsRequest\"X\n" +
	"\x1fAdminListPaymentMethodsResponse\x125\n" +
	"\amethods\x18\x01 \x03(\v2\x1b.payment.AdminPaymentMethodR\amethods2\xd5\t\n" +
	"\x0ePaymentService\x12M\n" +
	"\fCreateIntent\x12\x1c.payment.CreateIntentRequest\x1a\x1d.payment.CreateIntentResponse\"\x00\x12\\\n" +
	"\x11GetPaymentMethods\x12!.payment.GetPaymentMethodsRequest\x1a\".payment.GetPaymentMethodsResponse\"\x00\x12S\n" +
	"\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x1f.payment.ProcessPaymentResponse\"\x00\x12b\n" +
	"\x13SubmitManualPayment\x12#.payment.SubmitManualPaymentRequest\x1a$.payment.SubmitManualPaymentResponse\"\x00\x12b\n" +
	"\x13VerifyManualPayment\x12#.payment.VerifyManualPaymentRequest\x1a$.payment.VerifyManualPaymentResponse\"\x00\x12h\n" +
	"\x15GetIntentsByReference\x12%.payment.GetIntentsByReferenceRequest\x1a&.payment.GetIntentsByReferenceResponse\"\x00\x12q\n" +
	"\x18AdminCreatePaymentMethod\x12(.payment.AdminCreatePaymentMethodRequest\x1a).payment.AdminCreatePaymentMethodResponse\"\x00\x12q\n" +
	"\x18AdminUpdatePaymentMethod\x12(.payment.AdminUpdatePaymentMethodRequest\x1a).payment.AdminUpdatePaymentMethodResponse\"\x00\x12q\n" +
	"\x18AdminDeletePaymentMethod\x12(.payment.AdminDeletePaymentMethodRequest\x1a).payment.AdminDeletePaymentMethodResponse\"\x00\x12h\n" +
	"\x15AdminGetPaymentMethod\x12%.payment.AdminGetPaymentMethodRequest\x1a&.payment.AdminGetPaymentMethodResponse\"\x00\x12n\n" +
	"\x17AdminListPaymentMethods\x12'.payment.AdminListPaymentMethodsRequest\x1a(.payment.AdminListPaymentMethodsResponse\"\x00\x12\\\n" +
	"\x11AdminListPayments\x12!.payment.AdminListPaymentsRequest\x1a\".payment.AdminListPaymentsResponse\"\x00BDZBgithub.com/ybb-platform/payment/internal/infrastructure/grpc/protob\x06proto3"

var (
	file_payment_service_proto_rawDescOnce sync.Once
	file_payment_service_proto_rawDescData []byte
)

func file_payment_service_proto_rawDescGZIP() []byte {
	file_payment_service_proto_rawDescOnce.Do(func() {
		file_payment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)))
	})
	return file_payment_service_proto_rawDescData
}

var file_payment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_payment_service_proto_goTypes = []any{
	(*AdminListPaymentsRequest)(nil),         // 0: payment.AdminListPaymentsRequest
	(*AdminListPaymentsResponse)(nil),        // 1: payment.AdminListPaymentsResponse
	(*GetIntentsByReferenceRequest)(nil),     // 2: payment.GetIntentsByReferenceRequest
	(*PaymentIntent)(nil),                    // 3: payment.PaymentIntent
	(*ItemDetail)(nil),                       // 4: payment.ItemDetail
	(*GetIntentsByReferenceResponse)(nil),    // 5: payment.GetIntentsByReferenceResponse
	(*CreateIntentRequest)(nil),              // 6: payment.CreateIntentRequest
	(*CreateIntentResponse)(nil),             // 7: payment.CreateIntentResponse
	(*SubmitManualPaymentRequest)(nil),       // 8: payment.SubmitManualPaymentRequest
	(*SubmitManualPaymentResponse)(nil),      // 9: payment.SubmitManualPaymentResponse
	(*VerifyManualPaymentRequest)(nil),       // 10: payment.VerifyManualPaymentRequest
	(*VerifyManualPaymentResponse)(nil),      // 11: payment.VerifyManualPaymentResponse
	(*GetPaymentMethodsRequest)(nil),         // 12: payment.GetPaymentMethodsRequest
	(*PaymentMethod)(nil),                    // 13: payment.PaymentMethod
	(*GetPaymentMethodsResponse)(nil),        // 14: payment.GetPaymentMethodsResponse
	(*PaymentDetails)(nil),                   // 15: payment.PaymentDetails
	(*ProcessPaymentRequest)(nil),            // 16: payment.ProcessPaymentRequest
	(*ProcessPaymentAction)(nil),             // 17: payment.ProcessPaymentAction
	(*ProcessPaymentResponse)(nil),           // 18: payment.ProcessPaymentResponse
	(*FeeConfig)(nil),                        // 19: payment.FeeConfig
	(*AdminPaymentMethod)(nil),               // 20: payment.AdminPaymentMethod
	(*AdminCreatePaymentMethodRequest)(nil),  // 21: payment.AdminCreatePaymentMethodRequest
	(*AdminCreatePaymentMethodResponse)(nil), // 22: payment.AdminCreatePaymentMethodResponse
	(*AdminUpdatePaymentMethodRequest)(nil),  // 23: payment.AdminUpdatePaymentMethodRequest
	(*AdminUpdatePaymentMethodResponse)(nil), // 24: payment.AdminUpdatePaymentMethodResponse
	(*AdminDeletePaymentMethodRequest)(nil),  // 25: payment.AdminDeletePaymentMethodRequest
	(*AdminDeletePaymentMethodResponse)(nil), // 26: payment.AdminDeletePaymentMethodResponse
	(*AdminGetPaymentMethodRequest)(nil),     // 27: payment.AdminGetPaymentMethodRequest
	(*AdminGetPaymentMethodResponse)(nil),    // 28: payment.AdminGetPaymentMethodResponse
	(*AdminListPaymentMethodsRequest)(nil),   // 29: payment.AdminListPaymentMethodsRequest
	(*AdminListPaymentMethodsResponse)(nil),  // 30: payment.AdminListPaymentMethodsResponse
	nil,                                      // 31: payment.PaymentIntent.MetadataEntry
	nil,                                      // 32: payment.CreateIntentRequest.MetadataEntry
	nil,                                      // 33: payment.ProcessPaymentResponse.MetadataEntry
}
var file_payment_service_proto_depIdxs = []int32{
	3,  // 0: payment.AdminListPaymentsResponse.payments:type_name -> payment.PaymentIntent
	31, // 1: payment.PaymentIntent.metadata:type_name -> payment.PaymentIntent.MetadataEntry
	4,  // 2: payment.PaymentIntent.item_details:type_name -> payment.ItemDetail
	3,  // 3: payment.GetIntentsByReferenceResponse.intents:type_name -> payment.PaymentIntent
	32, // 4: payment.CreateIntentRequest.metadata:type_name -> payment.CreateIntentRequest.MetadataEntry
	4,  // 5: payment.CreateIntentRequest.item_details:type_name -> payment.ItemDetail
	13, // 6: payment.GetPaymentMethodsResponse.methods:type_name -> payment.PaymentMethod
	15, // 7: payment.ProcessPaymentRequest.payment_details:type_name -> payment.PaymentDetails
	17, // 8: payment.ProcessPaymentResponse.action:type_name -> payment.ProcessPaymentAction
	33, // 9: payment.ProcessPaymentResponse.metadata:type_name -> payment.ProcessPaymentResponse.MetadataEntry
	19, // 10: payment.AdminPaymentMethod.config:type_name -> payment.FeeConfig
	19, // 11: payment.AdminCreatePaymentMethodRequest.config:type_name -> payment.FeeConfig
	19, // 12: payment.AdminUpdatePaymentMethodRequest.config:type_name -> payment.FeeConfig
	20, // 13: payment.AdminGetPaymentMethodResponse.method:type_name -> payment.AdminPaymentMethod
	20, // 14: payment.AdminListPaymentMethodsResponse.methods:type_name -> payment.AdminPaymentMethod
	6,  // 15: payment.PaymentService.CreateIntent:input_type -> payment.CreateIntentRequest
	12, // 16: payment.PaymentService.GetPaymentMethods:input_type -> payment.GetPaymentMethodsRequest
	16, // 17: payment.PaymentService.ProcessPayment:input_type -> payment.ProcessPaymentRequest
	8,  // 18: payment.PaymentService.SubmitManualPayment:input_type -> payment.SubmitManualPaymentRequest
	10, // 19: payment.PaymentService.VerifyManualPayment:input_type -> payment.VerifyManualPaymentRequest
	2,  // 20: payment.PaymentService.GetIntentsByReference:input_type -> payment.GetIntentsByReferenceRequest
	21, // 21: payment.PaymentService.AdminCreatePaymentMethod:input_type -> payment.AdminCreatePaymentMethodRequest
	23, // 22: payment.PaymentService.AdminUpdatePaymentMethod:input_type -> payment.AdminUpdatePaymentMethodRequest
	25, // 23: payment.PaymentService.AdminDeletePaymentMethod:input_type -> payment.AdminDeletePaymentMethodRequest
	27, // 24: payment.PaymentService.AdminGetPaymentMethod:input_type -> payment.AdminGetPaymentMethodRequest
	29, // 25: payment.PaymentService.AdminListPaymentMethods:input_type -> payment.AdminListPaymentMethodsRequest
	0,  // 26: payment.PaymentService.AdminListPayments:input_type -> payment.AdminListPaymentsRequest
	7,  // 27: payment.PaymentService.CreateIntent:output_type -> payment.CreateIntentResponse
	14, // 28: payment.PaymentService.GetPaymentMethods:output_type -> payment.GetPaymentMethodsResponse
	18, // 29: payment.PaymentService.ProcessPayment:output_type -> payment.ProcessPaymentResponse
	9,  // 30: payment.PaymentService.SubmitManualPayment:output_type -> payment.SubmitManualPaymentResponse
	11, // 31: payment.PaymentService.VerifyManualPayment:output_type -> payment.VerifyManualPaymentResponse
	5,  // 32: payment.PaymentService.GetIntentsByReference:output_type -> payment.GetIntentsByReferenceResponse
	22, // 33: payment.PaymentService.AdminCreatePaymentMethod:output_type -> payment.AdminCreatePaymentMethodResponse
	24, // 34: payment.PaymentService.AdminUpdatePaymentMethod:output_type -> payment.AdminUpdatePaymentMethodResponse
	26, // 35: payment.PaymentService.AdminDeletePaymentMethod:output_type -> payment.AdminDeletePaymentMethodResponse
	28, // 36: payment.PaymentService.AdminGetPaymentMethod:output_type -> payment.AdminGetPaymentMethodResponse
	30, // 37: payment.PaymentService.AdminListPaymentMethods:output_type -> payment.AdminListPaymentMethodsResponse
	1,  // 38: payment.PaymentService.AdminListPayments:output_type -> payment.AdminListPaymentsResponse
	27, // [27:39] is the sub-list for method output_type
	15, // [15:27] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_payment_service_proto_init() }
func file_payment_service_proto_init() {
	if File_payment_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_proto_goTypes,
		DependencyIndexes: file_payment_service_proto_depIdxs,
		MessageInfos:      file_payment_service_proto_msgTypes,
	}.Build()
	File_payment_service_proto = out.File
	file_payment_service_proto_goTypes = nil
	file_payment_service_proto_depIdxs = nil
}
