// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: payment_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIntentsByReferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceType string                 `protobuf:"bytes,1,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,2,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntentsByReferenceRequest) Reset() {
	*x = GetIntentsByReferenceRequest{}
	mi := &file_payment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntentsByReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntentsByReferenceRequest) ProtoMessage() {}

func (x *GetIntentsByReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntentsByReferenceRequest.ProtoReflect.Descriptor instead.
func (*GetIntentsByReferenceRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetIntentsByReferenceRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *GetIntentsByReferenceRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type PaymentIntent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReferenceType string                 `protobuf:"bytes,7,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,8,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Snapshots of customer/item details
	CustomerName  string        `protobuf:"bytes,10,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerEmail string        `protobuf:"bytes,11,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	CustomerPhone string        `protobuf:"bytes,12,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	Description   string        `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	ItemDetails   []*ItemDetail `protobuf:"bytes,14,rep,name=item_details,json=itemDetails,proto3" json:"item_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentIntent) Reset() {
	*x = PaymentIntent{}
	mi := &file_payment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentIntent) ProtoMessage() {}

func (x *PaymentIntent) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentIntent.ProtoReflect.Descriptor instead.
func (*PaymentIntent) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentIntent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentIntent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentIntent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentIntent) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentIntent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentIntent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentIntent) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *PaymentIntent) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *PaymentIntent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PaymentIntent) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *PaymentIntent) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *PaymentIntent) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *PaymentIntent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PaymentIntent) GetItemDetails() []*ItemDetail {
	if x != nil {
		return x.ItemDetails
	}
	return nil
}

type ItemDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Brand         string                 `protobuf:"bytes,5,opt,name=brand,proto3" json:"brand,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	MerchantName  string                 `protobuf:"bytes,7,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDetail) Reset() {
	*x = ItemDetail{}
	mi := &file_payment_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDetail) ProtoMessage() {}

func (x *ItemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDetail.ProtoReflect.Descriptor instead.
func (*ItemDetail) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{2}
}

func (x *ItemDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemDetail) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemDetail) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemDetail) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ItemDetail) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ItemDetail) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

type GetIntentsByReferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intents       []*PaymentIntent       `protobuf:"bytes,1,rep,name=intents,proto3" json:"intents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntentsByReferenceResponse) Reset() {
	*x = GetIntentsByReferenceResponse{}
	mi := &file_payment_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntentsByReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntentsByReferenceResponse) ProtoMessage() {}

func (x *GetIntentsByReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntentsByReferenceResponse.ProtoReflect.Descriptor instead.
func (*GetIntentsByReferenceResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetIntentsByReferenceResponse) GetIntents() []*PaymentIntent {
	if x != nil {
		return x.Intents
	}
	return nil
}

type CreateIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"` // Optional
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	ReferenceType string                 `protobuf:"bytes,5,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,6,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Customer Info
	CustomerName  string `protobuf:"bytes,8,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerEmail string `protobuf:"bytes,9,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	CustomerPhone string `protobuf:"bytes,10,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	// Item Details
	Description   string        `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	ItemDetails   []*ItemDetail `protobuf:"bytes,12,rep,name=item_details,json=itemDetails,proto3" json:"item_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIntentRequest) Reset() {
	*x = CreateIntentRequest{}
	mi := &file_payment_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntentRequest) ProtoMessage() {}

func (x *CreateIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntentRequest.ProtoReflect.Descriptor instead.
func (*CreateIntentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateIntentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateIntentRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *CreateIntentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateIntentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateIntentRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *CreateIntentRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *CreateIntentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateIntentRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *CreateIntentRequest) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *CreateIntentRequest) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *CreateIntentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIntentRequest) GetItemDetails() []*ItemDetail {
	if x != nil {
		return x.ItemDetails
	}
	return nil
}

type CreateIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"` // Might be needed for some gateways, or empty
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIntentResponse) Reset() {
	*x = CreateIntentResponse{}
	mi := &file_payment_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntentResponse) ProtoMessage() {}

func (x *CreateIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntentResponse.ProtoReflect.Descriptor instead.
func (*CreateIntentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateIntentResponse) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *CreateIntentResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CreateIntentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubmitManualPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	ProofFileId   string                 `protobuf:"bytes,2,opt,name=proof_file_id,json=proofFileId,proto3" json:"proof_file_id,omitempty"` // optional if just using URL
	ProofFileUrl  string                 `protobuf:"bytes,3,opt,name=proof_file_url,json=proofFileUrl,proto3" json:"proof_file_url,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"` // notes from user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitManualPaymentRequest) Reset() {
	*x = SubmitManualPaymentRequest{}
	mi := &file_payment_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitManualPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitManualPaymentRequest) ProtoMessage() {}

func (x *SubmitManualPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitManualPaymentRequest.ProtoReflect.Descriptor instead.
func (*SubmitManualPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitManualPaymentRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetProofFileId() string {
	if x != nil {
		return x.ProofFileId
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetProofFileUrl() string {
	if x != nil {
		return x.ProofFileUrl
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type SubmitManualPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "PENDING_REVIEW"
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitManualPaymentResponse) Reset() {
	*x = SubmitManualPaymentResponse{}
	mi := &file_payment_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitManualPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitManualPaymentResponse) ProtoMessage() {}

func (x *SubmitManualPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitManualPaymentResponse.ProtoReflect.Descriptor instead.
func (*SubmitManualPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitManualPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitManualPaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type VerifyManualPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "SUCCESS", "FAILED"
	AdminId       string                 `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyManualPaymentRequest) Reset() {
	*x = VerifyManualPaymentRequest{}
	mi := &file_payment_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyManualPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyManualPaymentRequest) ProtoMessage() {}

func (x *VerifyManualPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyManualPaymentRequest.ProtoReflect.Descriptor instead.
func (*VerifyManualPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyManualPaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VerifyManualPaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VerifyManualPaymentRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *VerifyManualPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type VerifyManualPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyManualPaymentResponse) Reset() {
	*x = VerifyManualPaymentResponse{}
	mi := &file_payment_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyManualPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyManualPaymentResponse) ProtoMessage() {}

func (x *VerifyManualPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyManualPaymentResponse.ProtoReflect.Descriptor instead.
func (*VerifyManualPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyManualPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetPaymentMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodsRequest) Reset() {
	*x = GetPaymentMethodsRequest{}
	mi := &file_payment_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodsRequest) ProtoMessage() {}

func (x *GetPaymentMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodsRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetPaymentMethodsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetPaymentMethodsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PaymentMethod struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"` // e.g., "bank_transfer", "credit_card", "ewallet"
	ImageUrl string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// Fee details for user display
	EstimatedFee  float64 `protobuf:"fixed64,5,opt,name=estimated_fee,json=estimatedFee,proto3" json:"estimated_fee,omitempty"`
	IsSurcharge   bool    `protobuf:"varint,6,opt,name=is_surcharge,json=isSurcharge,proto3" json:"is_surcharge,omitempty"` // If true, UI should show "Fee: X" and "Total: Amount + Fee"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_payment_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{11}
}

func (x *PaymentMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentMethod) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PaymentMethod) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *PaymentMethod) GetEstimatedFee() float64 {
	if x != nil {
		return x.EstimatedFee
	}
	return 0
}

func (x *PaymentMethod) GetIsSurcharge() bool {
	if x != nil {
		return x.IsSurcharge
	}
	return false
}

type GetPaymentMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []*PaymentMethod       `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodsResponse) Reset() {
	*x = GetPaymentMethodsResponse{}
	mi := &file_payment_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodsResponse) ProtoMessage() {}

func (x *GetPaymentMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodsResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetPaymentMethodsResponse) GetMethods() []*PaymentMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

type PaymentDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arbitrary JSON string for gateway specific details
	DetailsJson   string `protobuf:"bytes,1,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentDetails) Reset() {
	*x = PaymentDetails{}
	mi := &file_payment_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentDetails) ProtoMessage() {}

func (x *PaymentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentDetails.ProtoReflect.Descriptor instead.
func (*PaymentDetails) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{13}
}

func (x *PaymentDetails) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

type ProcessPaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntentId        string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,2,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	GatewayToken    string                 `protobuf:"bytes,3,opt,name=gateway_token,json=gatewayToken,proto3" json:"gateway_token,omitempty"` // Token from Midtrans/Xendit JS SDK
	PaymentDetails  *PaymentDetails        `protobuf:"bytes,4,opt,name=payment_details,json=paymentDetails,proto3" json:"payment_details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_payment_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessPaymentRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetGatewayToken() string {
	if x != nil {
		return x.GatewayToken
	}
	return ""
}

func (x *ProcessPaymentRequest) GetPaymentDetails() *PaymentDetails {
	if x != nil {
		return x.PaymentDetails
	}
	return nil
}

type ProcessPaymentAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "redirect", "display_qr", "none"
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	QrString      string                 `protobuf:"bytes,3,opt,name=qr_string,json=qrString,proto3" json:"qr_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentAction) Reset() {
	*x = ProcessPaymentAction{}
	mi := &file_payment_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentAction) ProtoMessage() {}

func (x *ProcessPaymentAction) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentAction.ProtoReflect.Descriptor instead.
func (*ProcessPaymentAction) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessPaymentAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProcessPaymentAction) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProcessPaymentAction) GetQrString() string {
	if x != nil {
		return x.QrString
	}
	return ""
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "PENDING", "SUCCESS", "FAILED"
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Action        *ProcessPaymentAction  `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_payment_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_service_proto_rawDescGZIP(), []int{16}
}

func (x *ProcessPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessPaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ProcessPaymentResponse) GetAction() *ProcessPaymentAction {
	if x != nil {
		return x.Action
	}
	return nil
}

var File_payment_service_proto protoreflect.FileDescriptor

const file_payment_service_proto_rawDesc = "" +
	"\n" +
	"\x15payment_service.proto\x12\apayment\"h\n" +
	"\x1cGetIntentsByReferenceRequest\x12%\n" +
	"\x0ereference_type\x18\x01 \x01(\tR\rreferenceType\x12!\n" +
	"\freference_id\x18\x02 \x01(\tR\vreferenceId\"\xb9\x04\n" +
	"\rPaymentIntent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12%\n" +
	"\x0ereference_type\x18\a \x01(\tR\rreferenceType\x12!\n" +
	"\freference_id\x18\b \x01(\tR\vreferenceId\x12@\n" +
	"\bmetadata\x18\t \x03(\v2$.payment.PaymentIntent.MetadataEntryR\bmetadata\x12#\n" +
	"\rcustomer_name\x18\n" +
	" \x01(\tR\fcustomerName\x12%\n" +
	"\x0ecustomer_email\x18\v \x01(\tR\rcustomerEmail\x12%\n" +
	"\x0ecustomer_phone\x18\f \x01(\tR\rcustomerPhone\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x126\n" +
	"\fitem_details\x18\x0e \x03(\v2\x13.payment.ItemDetailR\vitemDetails\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\n" +
	"ItemDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05brand\x18\x05 \x01(\tR\x05brand\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12#\n" +
	"\rmerchant_name\x18\a \x01(\tR\fmerchantName\"Q\n" +
	"\x1dGetIntentsByReferenceResponse\x120\n" +
	"\aintents\x18\x01 \x03(\v2\x16.payment.PaymentIntentR\aintents\"\xa5\x04\n" +
	"\x13CreateIntentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12%\n" +
	"\x0ereference_type\x18\x05 \x01(\tR\rreferenceType\x12!\n" +
	"\freference_id\x18\x06 \x01(\tR\vreferenceId\x12F\n" +
	"\bmetadata\x18\a \x03(\v2*.payment.CreateIntentRequest.MetadataEntryR\bmetadata\x12#\n" +
	"\rcustomer_name\x18\b \x01(\tR\fcustomerName\x12%\n" +
	"\x0ecustomer_email\x18\t \x01(\tR\rcustomerEmail\x12%\n" +
	"\x0ecustomer_phone\x18\n" +
	" \x01(\tR\rcustomerPhone\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x126\n" +
	"\fitem_details\x18\f \x03(\v2\x13.payment.ItemDetailR\vitemDetails\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x14CreateIntentResponse\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x9d\x01\n" +
	"\x1aSubmitManualPaymentRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12\"\n" +
	"\rproof_file_id\x18\x02 \x01(\tR\vproofFileId\x12$\n" +
	"\x0eproof_file_url\x18\x03 \x01(\tR\fproofFileUrl\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\"\\\n" +
	"\x1bSubmitManualPaymentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"\x8e\x01\n" +
	"\x1aVerifyManualPaymentRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\tR\aadminId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"5\n" +
	"\x1bVerifyManualPaymentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"N\n" +
	"\x18GetPaymentMethodsRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xb4\x01\n" +
	"\rPaymentMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12#\n" +
	"\restimated_fee\x18\x05 \x01(\x01R\festimatedFee\x12!\n" +
	"\fis_surcharge\x18\x06 \x01(\bR\visSurcharge\"M\n" +
	"\x19GetPaymentMethodsResponse\x120\n" +
	"\amethods\x18\x01 \x03(\v2\x16.payment.PaymentMethodR\amethods\"3\n" +
	"\x0ePaymentDetails\x12!\n" +
	"\fdetails_json\x18\x01 \x01(\tR\vdetailsJson\"\xc7\x01\n" +
	"\x15ProcessPaymentRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12*\n" +
	"\x11payment_method_id\x18\x02 \x01(\tR\x0fpaymentMethodId\x12#\n" +
	"\rgateway_token\x18\x03 \x01(\tR\fgatewayToken\x12@\n" +
	"\x0fpayment_details\x18\x04 \x01(\v2\x17.payment.PaymentDetailsR\x0epaymentDetails\"Y\n" +
	"\x14ProcessPaymentAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1b\n" +
	"\tqr_string\x18\x03 \x01(\tR\bqrString\"\x8e\x01\n" +
	"\x16ProcessPaymentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x125\n" +
	"\x06action\x18\x03 \x01(\v2\x1d.payment.ProcessPaymentActionR\x06action2\xc4\x04\n" +
	"\x0ePaymentService\x12M\n" +
	"\fCreateIntent\x12\x1c.payment.CreateIntentRequest\x1a\x1d.payment.CreateIntentResponse\"\x00\x12\\\n" +
	"\x11GetPaymentMethods\x12!.payment.GetPaymentMethodsRequest\x1a\".payment.GetPaymentMethodsResponse\"\x00\x12S\n" +
	"\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x1f.payment.ProcessPaymentResponse\"\x00\x12b\n" +
	"\x13SubmitManualPayment\x12#.payment.SubmitManualPaymentRequest\x1a$.payment.SubmitManualPaymentResponse\"\x00\x12b\n" +
	"\x13VerifyManualPayment\x12#.payment.VerifyManualPaymentRequest\x1a$.payment.VerifyManualPaymentResponse\"\x00\x12h\n" +
	"\x15GetIntentsByReference\x12%.payment.GetIntentsByReferenceRequest\x1a&.payment.GetIntentsByReferenceResponse\"\x00BDZBgithub.com/ybb-platform/payment/internal/infrastructure/grpc/protob\x06proto3"

var (
	file_payment_service_proto_rawDescOnce sync.Once
	file_payment_service_proto_rawDescData []byte
)

func file_payment_service_proto_rawDescGZIP() []byte {
	file_payment_service_proto_rawDescOnce.Do(func() {
		file_payment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)))
	})
	return file_payment_service_proto_rawDescData
}

var file_payment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_payment_service_proto_goTypes = []any{
	(*GetIntentsByReferenceRequest)(nil),  // 0: payment.GetIntentsByReferenceRequest
	(*PaymentIntent)(nil),                 // 1: payment.PaymentIntent
	(*ItemDetail)(nil),                    // 2: payment.ItemDetail
	(*GetIntentsByReferenceResponse)(nil), // 3: payment.GetIntentsByReferenceResponse
	(*CreateIntentRequest)(nil),           // 4: payment.CreateIntentRequest
	(*CreateIntentResponse)(nil),          // 5: payment.CreateIntentResponse
	(*SubmitManualPaymentRequest)(nil),    // 6: payment.SubmitManualPaymentRequest
	(*SubmitManualPaymentResponse)(nil),   // 7: payment.SubmitManualPaymentResponse
	(*VerifyManualPaymentRequest)(nil),    // 8: payment.VerifyManualPaymentRequest
	(*VerifyManualPaymentResponse)(nil),   // 9: payment.VerifyManualPaymentResponse
	(*GetPaymentMethodsRequest)(nil),      // 10: payment.GetPaymentMethodsRequest
	(*PaymentMethod)(nil),                 // 11: payment.PaymentMethod
	(*GetPaymentMethodsResponse)(nil),     // 12: payment.GetPaymentMethodsResponse
	(*PaymentDetails)(nil),                // 13: payment.PaymentDetails
	(*ProcessPaymentRequest)(nil),         // 14: payment.ProcessPaymentRequest
	(*ProcessPaymentAction)(nil),          // 15: payment.ProcessPaymentAction
	(*ProcessPaymentResponse)(nil),        // 16: payment.ProcessPaymentResponse
	nil,                                   // 17: payment.PaymentIntent.MetadataEntry
	nil,                                   // 18: payment.CreateIntentRequest.MetadataEntry
}
var file_payment_service_proto_depIdxs = []int32{
	17, // 0: payment.PaymentIntent.metadata:type_name -> payment.PaymentIntent.MetadataEntry
	2,  // 1: payment.PaymentIntent.item_details:type_name -> payment.ItemDetail
	1,  // 2: payment.GetIntentsByReferenceResponse.intents:type_name -> payment.PaymentIntent
	18, // 3: payment.CreateIntentRequest.metadata:type_name -> payment.CreateIntentRequest.MetadataEntry
	2,  // 4: payment.CreateIntentRequest.item_details:type_name -> payment.ItemDetail
	11, // 5: payment.GetPaymentMethodsResponse.methods:type_name -> payment.PaymentMethod
	13, // 6: payment.ProcessPaymentRequest.payment_details:type_name -> payment.PaymentDetails
	15, // 7: payment.ProcessPaymentResponse.action:type_name -> payment.ProcessPaymentAction
	4,  // 8: payment.PaymentService.CreateIntent:input_type -> payment.CreateIntentRequest
	10, // 9: payment.PaymentService.GetPaymentMethods:input_type -> payment.GetPaymentMethodsRequest
	14, // 10: payment.PaymentService.ProcessPayment:input_type -> payment.ProcessPaymentRequest
	6,  // 11: payment.PaymentService.SubmitManualPayment:input_type -> payment.SubmitManualPaymentRequest
	8,  // 12: payment.PaymentService.VerifyManualPayment:input_type -> payment.VerifyManualPaymentRequest
	0,  // 13: payment.PaymentService.GetIntentsByReference:input_type -> payment.GetIntentsByReferenceRequest
	5,  // 14: payment.PaymentService.CreateIntent:output_type -> payment.CreateIntentResponse
	12, // 15: payment.PaymentService.GetPaymentMethods:output_type -> payment.GetPaymentMethodsResponse
	16, // 16: payment.PaymentService.ProcessPayment:output_type -> payment.ProcessPaymentResponse
	7,  // 17: payment.PaymentService.SubmitManualPayment:output_type -> payment.SubmitManualPaymentResponse
	9,  // 18: payment.PaymentService.VerifyManualPayment:output_type -> payment.VerifyManualPaymentResponse
	3,  // 19: payment.PaymentService.GetIntentsByReference:output_type -> payment.GetIntentsByReferenceResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_payment_service_proto_init() }
func file_payment_service_proto_init() {
	if File_payment_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_proto_goTypes,
		DependencyIndexes: file_payment_service_proto_depIdxs,
		MessageInfos:      file_payment_service_proto_msgTypes,
	}.Build()
	File_payment_service_proto = out.File
	file_payment_service_proto_goTypes = nil
	file_payment_service_proto_depIdxs = nil
}
