// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: payment_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_CreateIntent_FullMethodName             = "/payment.PaymentService/CreateIntent"
	PaymentService_GetPaymentMethods_FullMethodName        = "/payment.PaymentService/GetPaymentMethods"
	PaymentService_ProcessPayment_FullMethodName           = "/payment.PaymentService/ProcessPayment"
	PaymentService_SubmitManualPayment_FullMethodName      = "/payment.PaymentService/SubmitManualPayment"
	PaymentService_VerifyManualPayment_FullMethodName      = "/payment.PaymentService/VerifyManualPayment"
	PaymentService_GetIntentsByReference_FullMethodName    = "/payment.PaymentService/GetIntentsByReference"
	PaymentService_AdminCreatePaymentMethod_FullMethodName = "/payment.PaymentService/AdminCreatePaymentMethod"
	PaymentService_AdminUpdatePaymentMethod_FullMethodName = "/payment.PaymentService/AdminUpdatePaymentMethod"
	PaymentService_AdminDeletePaymentMethod_FullMethodName = "/payment.PaymentService/AdminDeletePaymentMethod"
	PaymentService_AdminGetPaymentMethod_FullMethodName    = "/payment.PaymentService/AdminGetPaymentMethod"
	PaymentService_AdminListPaymentMethods_FullMethodName  = "/payment.PaymentService/AdminListPaymentMethods"
	PaymentService_AdminListPayments_FullMethodName        = "/payment.PaymentService/AdminListPayments"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	// Create a payment intent (an order to pay)
	CreateIntent(ctx context.Context, in *CreateIntentRequest, opts ...grpc.CallOption) (*CreateIntentResponse, error)
	// Get available payment methods based on amount/currency
	GetPaymentMethods(ctx context.Context, in *GetPaymentMethodsRequest, opts ...grpc.CallOption) (*GetPaymentMethodsResponse, error)
	// Process a payment (charge) using a token from the frontend
	ProcessPayment(ctx context.Context, in *ProcessPaymentRequest, opts ...grpc.CallOption) (*ProcessPaymentResponse, error)
	// Manual Payment Support
	SubmitManualPayment(ctx context.Context, in *SubmitManualPaymentRequest, opts ...grpc.CallOption) (*SubmitManualPaymentResponse, error)
	VerifyManualPayment(ctx context.Context, in *VerifyManualPaymentRequest, opts ...grpc.CallOption) (*VerifyManualPaymentResponse, error)
	// Get intents by reference
	GetIntentsByReference(ctx context.Context, in *GetIntentsByReferenceRequest, opts ...grpc.CallOption) (*GetIntentsByReferenceResponse, error)
	// Admin: Payment Method Management
	AdminCreatePaymentMethod(ctx context.Context, in *AdminCreatePaymentMethodRequest, opts ...grpc.CallOption) (*AdminCreatePaymentMethodResponse, error)
	AdminUpdatePaymentMethod(ctx context.Context, in *AdminUpdatePaymentMethodRequest, opts ...grpc.CallOption) (*AdminUpdatePaymentMethodResponse, error)
	AdminDeletePaymentMethod(ctx context.Context, in *AdminDeletePaymentMethodRequest, opts ...grpc.CallOption) (*AdminDeletePaymentMethodResponse, error)
	AdminGetPaymentMethod(ctx context.Context, in *AdminGetPaymentMethodRequest, opts ...grpc.CallOption) (*AdminGetPaymentMethodResponse, error)
	AdminListPaymentMethods(ctx context.Context, in *AdminListPaymentMethodsRequest, opts ...grpc.CallOption) (*AdminListPaymentMethodsResponse, error)
	// Admin list payments
	AdminListPayments(ctx context.Context, in *AdminListPaymentsRequest, opts ...grpc.CallOption) (*AdminListPaymentsResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreateIntent(ctx context.Context, in *CreateIntentRequest, opts ...grpc.CallOption) (*CreateIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIntentResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreateIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPaymentMethods(ctx context.Context, in *GetPaymentMethodsRequest, opts ...grpc.CallOption) (*GetPaymentMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentMethodsResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetPaymentMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ProcessPayment(ctx context.Context, in *ProcessPaymentRequest, opts ...grpc.CallOption) (*ProcessPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessPaymentResponse)
	err := c.cc.Invoke(ctx, PaymentService_ProcessPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) SubmitManualPayment(ctx context.Context, in *SubmitManualPaymentRequest, opts ...grpc.CallOption) (*SubmitManualPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitManualPaymentResponse)
	err := c.cc.Invoke(ctx, PaymentService_SubmitManualPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) VerifyManualPayment(ctx context.Context, in *VerifyManualPaymentRequest, opts ...grpc.CallOption) (*VerifyManualPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyManualPaymentResponse)
	err := c.cc.Invoke(ctx, PaymentService_VerifyManualPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetIntentsByReference(ctx context.Context, in *GetIntentsByReferenceRequest, opts ...grpc.CallOption) (*GetIntentsByReferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIntentsByReferenceResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetIntentsByReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) AdminCreatePaymentMethod(ctx context.Context, in *AdminCreatePaymentMethodRequest, opts ...grpc.CallOption) (*AdminCreatePaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreatePaymentMethodResponse)
	err := c.cc.Invoke(ctx, PaymentService_AdminCreatePaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) AdminUpdatePaymentMethod(ctx context.Context, in *AdminUpdatePaymentMethodRequest, opts ...grpc.CallOption) (*AdminUpdatePaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpdatePaymentMethodResponse)
	err := c.cc.Invoke(ctx, PaymentService_AdminUpdatePaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) AdminDeletePaymentMethod(ctx context.Context, in *AdminDeletePaymentMethodRequest, opts ...grpc.CallOption) (*AdminDeletePaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeletePaymentMethodResponse)
	err := c.cc.Invoke(ctx, PaymentService_AdminDeletePaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) AdminGetPaymentMethod(ctx context.Context, in *AdminGetPaymentMethodRequest, opts ...grpc.CallOption) (*AdminGetPaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminGetPaymentMethodResponse)
	err := c.cc.Invoke(ctx, PaymentService_AdminGetPaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) AdminListPaymentMethods(ctx context.Context, in *AdminListPaymentMethodsRequest, opts ...grpc.CallOption) (*AdminListPaymentMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListPaymentMethodsResponse)
	err := c.cc.Invoke(ctx, PaymentService_AdminListPaymentMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) AdminListPayments(ctx context.Context, in *AdminListPaymentsRequest, opts ...grpc.CallOption) (*AdminListPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListPaymentsResponse)
	err := c.cc.Invoke(ctx, PaymentService_AdminListPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	// Create a payment intent (an order to pay)
	CreateIntent(context.Context, *CreateIntentRequest) (*CreateIntentResponse, error)
	// Get available payment methods based on amount/currency
	GetPaymentMethods(context.Context, *GetPaymentMethodsRequest) (*GetPaymentMethodsResponse, error)
	// Process a payment (charge) using a token from the frontend
	ProcessPayment(context.Context, *ProcessPaymentRequest) (*ProcessPaymentResponse, error)
	// Manual Payment Support
	SubmitManualPayment(context.Context, *SubmitManualPaymentRequest) (*SubmitManualPaymentResponse, error)
	VerifyManualPayment(context.Context, *VerifyManualPaymentRequest) (*VerifyManualPaymentResponse, error)
	// Get intents by reference
	GetIntentsByReference(context.Context, *GetIntentsByReferenceRequest) (*GetIntentsByReferenceResponse, error)
	// Admin: Payment Method Management
	AdminCreatePaymentMethod(context.Context, *AdminCreatePaymentMethodRequest) (*AdminCreatePaymentMethodResponse, error)
	AdminUpdatePaymentMethod(context.Context, *AdminUpdatePaymentMethodRequest) (*AdminUpdatePaymentMethodResponse, error)
	AdminDeletePaymentMethod(context.Context, *AdminDeletePaymentMethodRequest) (*AdminDeletePaymentMethodResponse, error)
	AdminGetPaymentMethod(context.Context, *AdminGetPaymentMethodRequest) (*AdminGetPaymentMethodResponse, error)
	AdminListPaymentMethods(context.Context, *AdminListPaymentMethodsRequest) (*AdminListPaymentMethodsResponse, error)
	// Admin list payments
	AdminListPayments(context.Context, *AdminListPaymentsRequest) (*AdminListPaymentsResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreateIntent(context.Context, *CreateIntentRequest) (*CreateIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIntent not implemented")
}
func (UnimplementedPaymentServiceServer) GetPaymentMethods(context.Context, *GetPaymentMethodsRequest) (*GetPaymentMethodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentMethods not implemented")
}
func (UnimplementedPaymentServiceServer) ProcessPayment(context.Context, *ProcessPaymentRequest) (*ProcessPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPayment not implemented")
}
func (UnimplementedPaymentServiceServer) SubmitManualPayment(context.Context, *SubmitManualPaymentRequest) (*SubmitManualPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitManualPayment not implemented")
}
func (UnimplementedPaymentServiceServer) VerifyManualPayment(context.Context, *VerifyManualPaymentRequest) (*VerifyManualPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyManualPayment not implemented")
}
func (UnimplementedPaymentServiceServer) GetIntentsByReference(context.Context, *GetIntentsByReferenceRequest) (*GetIntentsByReferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIntentsByReference not implemented")
}
func (UnimplementedPaymentServiceServer) AdminCreatePaymentMethod(context.Context, *AdminCreatePaymentMethodRequest) (*AdminCreatePaymentMethodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminCreatePaymentMethod not implemented")
}
func (UnimplementedPaymentServiceServer) AdminUpdatePaymentMethod(context.Context, *AdminUpdatePaymentMethodRequest) (*AdminUpdatePaymentMethodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpdatePaymentMethod not implemented")
}
func (UnimplementedPaymentServiceServer) AdminDeletePaymentMethod(context.Context, *AdminDeletePaymentMethodRequest) (*AdminDeletePaymentMethodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeletePaymentMethod not implemented")
}
func (UnimplementedPaymentServiceServer) AdminGetPaymentMethod(context.Context, *AdminGetPaymentMethodRequest) (*AdminGetPaymentMethodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminGetPaymentMethod not implemented")
}
func (UnimplementedPaymentServiceServer) AdminListPaymentMethods(context.Context, *AdminListPaymentMethodsRequest) (*AdminListPaymentMethodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListPaymentMethods not implemented")
}
func (UnimplementedPaymentServiceServer) AdminListPayments(context.Context, *AdminListPaymentsRequest) (*AdminListPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListPayments not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreateIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreateIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateIntent(ctx, req.(*CreateIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPaymentMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetPaymentMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentMethods(ctx, req.(*GetPaymentMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ProcessPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ProcessPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ProcessPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ProcessPayment(ctx, req.(*ProcessPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_SubmitManualPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitManualPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).SubmitManualPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_SubmitManualPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).SubmitManualPayment(ctx, req.(*SubmitManualPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_VerifyManualPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyManualPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).VerifyManualPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_VerifyManualPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).VerifyManualPayment(ctx, req.(*VerifyManualPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetIntentsByReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntentsByReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetIntentsByReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetIntentsByReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetIntentsByReference(ctx, req.(*GetIntentsByReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_AdminCreatePaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreatePaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).AdminCreatePaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_AdminCreatePaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).AdminCreatePaymentMethod(ctx, req.(*AdminCreatePaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_AdminUpdatePaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdatePaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).AdminUpdatePaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_AdminUpdatePaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).AdminUpdatePaymentMethod(ctx, req.(*AdminUpdatePaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_AdminDeletePaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeletePaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).AdminDeletePaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_AdminDeletePaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).AdminDeletePaymentMethod(ctx, req.(*AdminDeletePaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_AdminGetPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGetPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).AdminGetPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_AdminGetPaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).AdminGetPaymentMethod(ctx, req.(*AdminGetPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_AdminListPaymentMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListPaymentMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).AdminListPaymentMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_AdminListPaymentMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).AdminListPaymentMethods(ctx, req.(*AdminListPaymentMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_AdminListPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).AdminListPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_AdminListPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).AdminListPayments(ctx, req.(*AdminListPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIntent",
			Handler:    _PaymentService_CreateIntent_Handler,
		},
		{
			MethodName: "GetPaymentMethods",
			Handler:    _PaymentService_GetPaymentMethods_Handler,
		},
		{
			MethodName: "ProcessPayment",
			Handler:    _PaymentService_ProcessPayment_Handler,
		},
		{
			MethodName: "SubmitManualPayment",
			Handler:    _PaymentService_SubmitManualPayment_Handler,
		},
		{
			MethodName: "VerifyManualPayment",
			Handler:    _PaymentService_VerifyManualPayment_Handler,
		},
		{
			MethodName: "GetIntentsByReference",
			Handler:    _PaymentService_GetIntentsByReference_Handler,
		},
		{
			MethodName: "AdminCreatePaymentMethod",
			Handler:    _PaymentService_AdminCreatePaymentMethod_Handler,
		},
		{
			MethodName: "AdminUpdatePaymentMethod",
			Handler:    _PaymentService_AdminUpdatePaymentMethod_Handler,
		},
		{
			MethodName: "AdminDeletePaymentMethod",
			Handler:    _PaymentService_AdminDeletePaymentMethod_Handler,
		},
		{
			MethodName: "AdminGetPaymentMethod",
			Handler:    _PaymentService_AdminGetPaymentMethod_Handler,
		},
		{
			MethodName: "AdminListPaymentMethods",
			Handler:    _PaymentService_AdminListPaymentMethods_Handler,
		},
		{
			MethodName: "AdminListPayments",
			Handler:    _PaymentService_AdminListPayments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment_service.proto",
}
