import { CommandHandler, ICommandHandler } from '@nestjs/cqrs';
import { Inject } from '@nestjs/common';
import { CreateBrandCommand } from '../create-brand.command';
import { IBrandRepository } from '@core/interfaces/repositories/brand.repository.interface';
import { Brand } from '@core/entities/brand.entity';
import { IUserActivityLogRepository } from '@core/interfaces/repositories/user-activity-log.repository.interface';
import { StorageService } from '../../../../files/application/storage.service';
import { UserActivityLog } from '@core/entities/user-activity-log.entity';
import { LandingRevalidationService } from '../../services/landing-revalidation.service';
import { BrandLogoAssetsService } from '../../services/brand-logo-assets.service';
import { PrismaService } from '@shared/infrastructure/prisma/prisma.service';
import { Prisma } from '@prisma/client';
import { ensureBrandIdentityAvailable } from '../../../shared/brand-identity.utils';

@CommandHandler(CreateBrandCommand)
export class CreateBrandHandler implements ICommandHandler<CreateBrandCommand> {
    constructor(
        @Inject('IBrandRepository')
        private readonly brandRepository: IBrandRepository,
        @Inject(IUserActivityLogRepository)
        private readonly activityLogRepository: IUserActivityLogRepository,
        private readonly storageService: StorageService,
        private readonly brandLogoAssetsService: BrandLogoAssetsService,
        private readonly prisma: PrismaService,
        private readonly landingRevalidation: LandingRevalidationService,
    ) {}

    async execute(command: CreateBrandCommand): Promise<Brand> {
        const { dto, userId, files } = command;
        
        if (!dto.slug) {
            dto.slug = this.generateSlug(dto.name);
        }

        await ensureBrandIdentityAvailable(this.brandRepository, {
            name: dto.name,
            slug: dto.slug,
        });

        // We temporarily create the brand to get its ID, or we assume ID is generated by DB.
        // If ID is generated by DB, we can't use it for folder structure unless we modify the entity AFTER creation.
        // However, generic practice here from Gallery is using BrandID as the "Bucket" or logic holder.
        // But BrandID IS the entity we are creating. 
        // For now, let's use 'brands' as the category logic.
        
        // Wait, file upload needs a "Brand ID" (Program Category ID) for ownership/pathing in older Logic.
        // But here we ARE creating the Brand.
        // We can just use a placeholder or 'global'.
        // Or cleaner: Create brand first, then upload, then update brand. 
        
        // Let's create the brand first to get ID.
        let brand = await this.brandRepository.create(dto);
        const updates: Record<string, unknown> = {};
        let needsUpdate = false;
        let metadataPatch: Record<string, string> | null = null;

        if (files) {
              if (files.logo) {
                const logoAssets = await this.brandLogoAssetsService.uploadBrandLogoAssets(
                    files.logo,
                    brand.id,
                );
                updates.logoUrl = logoAssets.logoUrl;
                updates.logoIconUrl = logoAssets.logoIconUrl;
                metadataPatch = logoAssets.metadataPatch;
                needsUpdate = true;
            }

            if (files.banner) {
                const result = await this.storageService.uploadFile(
                    files.banner,
                    userId,
                    brand.id,
                    'brands/banners',
                    undefined
                );
                updates.bannerUrl = result.url;
                needsUpdate = true;
            }
        }

        if (!metadataPatch && dto.logoUrl) {
            updates.logoIconUrl = dto.logoUrl;
            metadataPatch = {
                favicon_url: dto.logoUrl,
                apple_icon_url: dto.logoUrl,
            };
            needsUpdate = true;
        }

        if (needsUpdate) {
            brand = await this.brandRepository.update(brand.id, updates as Partial<Brand>);
        }

        if (metadataPatch) {
            const existingMetadata = await this.brandRepository.getMetadata(brand.id);
            await this.prisma.brand.update({
                where: { id: brand.id },
                data: {
                    metadata: {
                        ...(existingMetadata ?? {}),
                        ...metadataPatch,
                    } as Prisma.InputJsonValue,
                },
            });
        }

        // Log activity
        await this.activityLogRepository.create(new UserActivityLog(
            undefined as unknown as string,
            userId,
            'CREATE_BRAND',
            'BRAND',
            {
                brandId: brand.id,
                brandName: brand.name,
            },
            null,
            null,
            null,
            null,
            null,
            null,
            new Date(),
        ));

        await this.landingRevalidation.revalidateForBrand(brand.id, {
            landingUrl: brand.landingUrl,
            websiteUrl: brand.websiteUrl,
        });
        return brand;
    }

    private generateSlug(text: string): string {
        // Cap at the Brand.slug column limit (VarChar(100), see prisma/schema/program.prisma).
        // Not routed through shared/utils/auto-slug.ts: that util is separator-incompatible
        // here (underscore-joined, built for form-field keys) and would rewrite every
        // brand slug in prod off its established hyphenated convention (e.g.
        // "istanbul-youth-summit"). This transform chain only ever removes characters,
        // so slicing after is a safe hard cap, not a truncation that changes earlier chars.
        return text
            .toString()
            .toLowerCase()
            .trim()
            .replace(/\s+/g, '-')     // Replace spaces with -
            .replace(/[^\w-]+/g, '') // Remove all non-word chars
            .replace(/--+/g, '-')  // Replace multiple - with single -
            .slice(0, 100);
    }
}
