import { CommandHandler, ICommandHandler } from '@nestjs/cqrs';
import { Inject } from '@nestjs/common';
import { CreateBrandCommand } from '../create-brand.command';
import { IBrandRepository } from '@core/interfaces/repositories/brand.repository.interface';
import { Brand } from '@core/entities/brand.entity';
import { IUserActivityLogRepository } from '@core/interfaces/repositories/user-activity-log.repository.interface';
import { StorageService } from '../../../../files/application/storage.service';
import { UserActivityLog } from '@core/entities/user-activity-log.entity';

@CommandHandler(CreateBrandCommand)
export class CreateBrandHandler implements ICommandHandler<CreateBrandCommand> {
    constructor(
        @Inject('IBrandRepository')
        private readonly brandRepository: IBrandRepository,
        @Inject(IUserActivityLogRepository)
        private readonly activityLogRepository: IUserActivityLogRepository,
        private readonly storageService: StorageService,
    ) {}

    async execute(command: CreateBrandCommand): Promise<Brand> {
        const { dto, userId, files } = command;
        
        if (!dto.slug) {
            dto.slug = this.generateSlug(dto.name);
        }

        // We temporarily create the brand to get its ID, or we assume ID is generated by DB.
        // If ID is generated by DB, we can't use it for folder structure unless we modify the entity AFTER creation.
        // However, generic practice here from Gallery is using BrandID as the "Bucket" or logic holder.
        // But BrandID IS the entity we are creating. 
        // For now, let's use 'brands' as the category logic.
        
        // Wait, file upload needs a "Brand ID" (Program Category ID) for ownership/pathing in older Logic.
        // But here we ARE creating the Brand.
        // We can just use a placeholder or 'global'.
        // Or cleaner: Create brand first, then upload, then update brand. 
        
        // Let's create the brand first to get ID.
        let brand = await this.brandRepository.create(dto);
        const updates: Record<string, unknown> = {};
        let needsUpdate = false;

        if (files) {
             if (files.logo) {
                const result = await this.storageService.uploadFile(
                    files.logo,
                    userId,
                    brand.id, // Now we have the brand ID
                    'brands/logos',
                    undefined 
                );
                updates.logoUrl = result.url;
                needsUpdate = true;
            }

            if (files.banner) {
                const result = await this.storageService.uploadFile(
                    files.banner,
                    userId,
                    brand.id,
                    'brands/banners',
                    undefined
                );
                updates.bannerUrl = result.url;
                needsUpdate = true;
            }
        }

        if (needsUpdate) {
            brand = await this.brandRepository.update(brand.id, updates as Partial<Brand>);
        }

        // Log activity
        await this.activityLogRepository.create(new UserActivityLog(
            undefined as unknown as string,
            userId,
            'CREATE_BRAND',
            'BRAND',
            {
                brandId: brand.id,
                brandName: brand.name,
            },
            null,
            null,
            null,
            null,
            null,
            null,
            new Date(),
        ));

        return brand;
    }

    private generateSlug(text: string): string {
        return text
            .toString()
            .toLowerCase()
            .trim()
            .replace(/\s+/g, '-')     // Replace spaces with -
            .replace(/[^\w\-]+/g, '') // Remove all non-word chars
            .replace(/\-\-+/g, '-');  // Replace multiple - with single -
    }
}
