# Development Dockerfile
FROM node:20-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm config set fetch-retry-maxtimeout 600000 && \
    npm config set fetch-retries 5 && \
    npm install

# Copy project files
COPY . .

# Expose port
EXPOSE 4003

# Run in development mode (no build needed)
CMD ["npm", "run", "dev", "--", "-p", "4003"]
