services:
  # =========================================
  # Minimal Admin (Staging)
  # =========================================
  minimal-admin:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ybb-minimal-admin-staging
    restart: always
    ports:
      - "4003:4003"
    env_file:
      - .env.staging
    networks:
      - ybb-network-staging

networks:
  ybb-network-staging:
    name: ybb-network-staging
    external: true
