services:
  # =========================================
  # Minimal Admin
  # =========================================
  minimal-admin:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ybb-minimal-admin
    restart: unless-stopped
    ports:
      - "4003:4003"
    env_file:
      - .env
    environment:
      # Overrides
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default
