// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/payment-methods": {
            "get": {
                "description": "Get a list of all available payment methods",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Methods"
                ],
                "summary": "Get All Payment Methods",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/entities.PaymentMethodEntity"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new bank or payment method to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Methods"
                ],
                "summary": "Add New Payment Method",
                "parameters": [
                    {
                        "description": "Payment Method Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.PaymentMethodEntity"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/entities.PaymentMethodEntity"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payment-methods/{id}": {
            "get": {
                "description": "Get payment method details by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Methods"
                ],
                "summary": "Get Payment Method Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment Method ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/entities.PaymentMethodEntity"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Update bank or payment method details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Methods"
                ],
                "summary": "Update Payment Method",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment Method ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.PaymentMethodEntity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/entities.PaymentMethodEntity"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete (Soft Delete) payment method by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment Methods"
                ],
                "summary": "Delete Payment Method",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment Method ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payments": {
            "post": {
                "description": "Create a new payment intent and get checkout information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Create Payment Intent",
                "parameters": [
                    {
                        "description": "Payment Request Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePaymentDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payments/user/{userId}": {
            "get": {
                "description": "Get list of payments for a user with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Get User's Payments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit (default 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payments/{id}": {
            "get": {
                "description": "Get payment details by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Get Payment Details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payments/{id}/cancel": {
            "post": {
                "description": "Cancel a pending payment",
                "tags": [
                    "Payments"
                ],
                "summary": "Cancel Payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payments/{id}/proof": {
            "post": {
                "description": "Menerima URL Bukti Transfer yang sudah diupload oleh API/File Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manual Payment"
                ],
                "summary": "Upload Bukti Transfer (Submit URL)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data File (ID \u0026 URL)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UploadProofReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payments/{id}/refund": {
            "post": {
                "description": "Refunds a successful payment",
                "tags": [
                    "Payments"
                ],
                "summary": "Refund Payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaymentResponseDTO"
                        }
                    }
                }
            }
        },
        "/payments/{id}/retry": {
            "post": {
                "description": "Create a new transaction based on failed/expired payment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Retry Payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Old Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaymentResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payments/{id}/verify": {
            "post": {
                "description": "Admin menyetujui (Approve) atau menolak (Reject) pembayaran manual",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manual Payment"
                ],
                "summary": "Verifikasi Pembayaran (Admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data Verifikasi (Action \u0026 Admin ID)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.VerifyPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/payments/{id}/verify-status": {
            "post": {
                "description": "Check payment status from Gateway (now disabled/noop)",
                "tags": [
                    "Payments"
                ],
                "summary": "Verify Payment Status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreatePaymentDTO": {
            "type": "object",
            "required": [
                "amount",
                "application_id",
                "currency",
                "customer_email",
                "customer_name",
                "gateway_name",
                "payment_method",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "application_id": {
                    "type": "string"
                },
                "callback_url": {
                    "description": "Optional: Callback URL for frontend redirect",
                    "type": "string"
                },
                "currency": {
                    "description": "\"IDR\", \"USD\", etc.",
                    "type": "string"
                },
                "customer_email": {
                    "type": "string"
                },
                "customer_name": {
                    "description": "Customer information",
                    "type": "string"
                },
                "customer_phone": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "gateway_name": {
                    "description": "\"midtrans\", \"stripe\", etc.",
                    "type": "string"
                },
                "payment_method": {
                    "description": "\"credit_card\", \"bank_transfer\", etc.",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.PaymentResponseDTO": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "application_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "gateway_name": {
                    "type": "string"
                },
                "gateway_order_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "paid_at": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "payment_type": {
                    "type": "string"
                },
                "redirect_url": {
                    "description": "URL to complete payment",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "entities.PaymentMethodEntity": {
            "type": "object",
            "properties": {
                "account_name": {
                    "type": "string",
                    "example": "PT YBB Platform"
                },
                "account_number": {
                    "type": "string",
                    "example": "1234567890"
                },
                "admin_instructions": {
                    "type": "string",
                    "example": "Cek mutasi bank tanggal sekian"
                },
                "bank_name": {
                    "description": "--- Manual Payment Fields ---",
                    "type": "string",
                    "example": "BCA"
                },
                "code": {
                    "description": "e.g., \"bank_bca\", \"midtrans\", \"gopay\"",
                    "type": "string"
                },
                "created_at": {
                    "description": "--- Timestamps ---",
                    "type": "string",
                    "example": "2025-12-01T10:00:00Z"
                },
                "description": {
                    "type": "string"
                },
                "displayName": {
                    "description": "User-facing name",
                    "type": "string"
                },
                "gateway_name": {
                    "description": "--- Automatic Payment Fields ---",
                    "type": "string",
                    "example": ""
                },
                "gateway_type": {
                    "type": "string",
                    "example": ""
                },
                "icon": {
                    "description": "Icon URL or identifier",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "instructions": {
                    "type": "string",
                    "example": "Silakan transfer sesuai nominal unik"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "description": "e.g., \"Bank BCA\", \"Midtrans\", \"GoPay\"",
                    "type": "string"
                },
                "requires_proof": {
                    "type": "boolean",
                    "example": true
                },
                "sort_order": {
                    "type": "integer",
                    "example": 1
                },
                "type": {
                    "$ref": "#/definitions/entities.PaymentMethodType"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-12-01T10:00:00Z"
                }
            }
        },
        "entities.PaymentMethodType": {
            "type": "string",
            "enum": [
                "automatic",
                "manual"
            ],
            "x-enum-comments": {
                "MethodTypeAutomatic": "Via payment gateway",
                "MethodTypeManual": "Manual verification"
            },
            "x-enum-descriptions": [
                "Via payment gateway",
                "Manual verification"
            ],
            "x-enum-varnames": [
                "MethodTypeAutomatic",
                "MethodTypeManual"
            ]
        },
        "handlers.UploadProofReq": {
            "type": "object",
            "properties": {
                "file_id": {
                    "type": "string"
                },
                "file_url": {
                    "type": "string"
                }
            }
        },
        "handlers.VerifyPaymentRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "\"approve\" or \"reject\"",
                    "type": "string"
                },
                "admin_id": {
                    "description": "Simulated Admin ID",
                    "type": "string"
                },
                "reason": {
                    "description": "Required if rejected",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8002",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "YBB Payment Service API",
	Description:      "This is the API documentation for the YBB Platform Payment Service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
