import { Injectable, Inject, ConflictException } from '@nestjs/common';
import { ClientProxy } from '@nestjs/microservices';
import { CreateUserCommand } from '../create-user.command';
import { UserResponseDto } from '@modules/users/presentation/dto/user-response.dto';
import { IUserRepository } from '@core/interfaces/repositories/user.repository.interface';
import { User } from '@core/entities/user.entity';
import * as bcrypt from 'bcrypt';

@Injectable()
export class CreateUserHandler {
  constructor(
    @Inject(IUserRepository)
    private readonly userRepository: IUserRepository,
    @Inject('NOTIFICATION_SERVICE') private readonly notificationClient: ClientProxy,
  ) { }

  async execute(command: CreateUserCommand): Promise<UserResponseDto> {
    // Check if user already exists
    const exists = await this.userRepository.exists(command.email, command.brandId);
    if (exists) {
      throw new ConflictException(
        `User with email ${command.email} already exists in brand ${command.brandId}`,
      );
    }

    // Hash password
    const passwordHash = await bcrypt.hash(command.password, 10);

    // Create user entity
    const user = new User(
      '', // ID will be generated by database
      command.brandId,
      command.email,
      true, // isActive
      false, // emailVerified
      new Date(),
      new Date(),
    );

    // Save to repository
    const createdUser = await this.userRepository.create(user, passwordHash);

    // Emit event
    this.notificationClient.emit('user.registered', {
      email: createdUser.email,
      name: 'User',
    });

    // Return DTO
    return this.toDto(createdUser);
  }

  private toDto(user: User): UserResponseDto {
    return {
      id: user.id,
      brandId: user.brandId,
      email: user.email,
      isActive: user.isActive,
      emailVerified: user.emailVerified,
      createdAt: user.createdAt,
      updatedAt: user.updatedAt,
    };
  }
}
