import { Injectable, Inject, ConflictException } from '@nestjs/common';
import { CreateUserCommand } from '../create-user.command';
import { UserResponseDto } from '@modules/users/presentation/dto/user-response.dto';
import { IUserRepository } from '@core/interfaces/repositories/user.repository.interface';
import { User } from '@core/entities/user.entity';
import { RabbitMQProducerService } from '../../../../../shared/infrastructure/rabbitmq/rabbitmq-producer.service';
import { CacheService } from '../../../../../shared/infrastructure/cache/cache.service';
import { CACHE_KEYS } from '../../../../../shared/constants/cache-keys';
import * as bcrypt from 'bcrypt';

@Injectable()
export class CreateUserHandler {
  constructor(
    @Inject(IUserRepository)
    private readonly userRepository: IUserRepository,
    private readonly rabbitmqProducer: RabbitMQProducerService,
    private readonly cacheService: CacheService,
  ) { }

  async execute(command: CreateUserCommand): Promise<UserResponseDto> {
    // Check if user already exists
    const exists = await this.userRepository.exists(command.email, command.brandId);
    if (exists) {
      throw new ConflictException(
        `User with email ${command.email} already exists in brand ${command.brandId}`,
      );
    }

    // Hash password
    const passwordHash = await bcrypt.hash(command.password, 10);

    // Create user entity
    const user = new User(
      '', // ID will be generated by database
      command.brandId,
      command.email,
      true, // isActive
      false, // emailVerified
      new Date(),
      new Date(),
    );

    // Save to repository
    const createdUser = await this.userRepository.create(user, passwordHash);

    // Emit event
    this.rabbitmqProducer.emit('user.registered', {
      email: createdUser.email,
      name: 'User',
    });

    // Invalidate user list cache for this brand
    // We use a wildcard pattern to match all pagination pages and roles
    // Also clears the platform-wide listing, keyed `user:list:all:*`, which a
    // brand-specific pattern never matched - so a cross-brand list kept showing
    // a stale roster after a user was created.
    await Promise.all([
      this.cacheService.invalidateByPattern(`user:list:${command.brandId}:*`),
      this.cacheService.invalidateByPattern('user:list:all:*'),
    ]);

    // Return DTO
    return this.toDto(createdUser);
  }

  private toDto(user: User): UserResponseDto {
    return {
      id: user.id,
      brandId: user.brandId,
      email: user.email,
      isActive: user.isActive,
      emailVerified: user.emailVerified,
      createdAt: user.createdAt,
      updatedAt: user.updatedAt,
    };
  }
}
