services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ybb-prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.local.yml:/etc/prometheus/prometheus.yml.tpl
      - ./prometheus/docker-entrypoint.sh:/etc/prometheus/docker-entrypoint.sh
      - prometheus_data:/prometheus
    entrypoint: [ "/bin/sh", "/etc/prometheus/docker-entrypoint.sh" ]
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    env_file:
      - .env.prod
    ports:
      - "9090:9090"
    networks:
      - ybb-network

  grafana:
    image: grafana/grafana:latest
    container_name: ybb-grafana
    restart: always
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    env_file:
      - .env.prod
    networks:
      - ybb-network
    ports:
      - "3001:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`monitor.ybbhub.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  loki:
    image: grafana/loki:3.0.0
    container_name: ybb-loki
    restart: always
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/tmp/loki
    env_file:
      - .env.prod
    networks:
      - ybb-network

  tempo:
    image: grafana/tempo:2.4.1
    container_name: ybb-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo-config.yml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    env_file:
      - .env.prod
    networks:
      - ybb-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    container_name: ybb-otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel/otel-collector-config.yml:/etc/otel-collector-config.yaml
    env_file:
      - .env.prod
    networks:
      - ybb-network
    depends_on:
      - tempo

networks:
  ybb-network:
    name: ybb-network
    external: true

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  tempo_data:
